### ISSUE TITLE
Теги использованные нуль раз

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#1]
Есть тег(и) [использованные нуль раз](https://anime-pictures.net/pictures/view_all_tags/0?lang=ru&search_text=heshi+ri+man+flag+%28game%29&tag_desc=). Ещё был удалённый тег, на который можно было подписаться, но уже починился.

**Comment by stalkerg** [comment]
Ещё 3 таких тега нашёл - почистил и удалил. Все они достаточно старые так что есть шанс, что только тогда была какая то ошибка. 
Что бы удалить такие теги достаточно просто их кудато добавить и потом опять удалить.
