### ISSUE TITLE
Нельзя искать картинки по статусу

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#10]
Обычным пользователям не удобно искать прешки затесавшиеся между опубликованными, как результат на прешках теги могут появится только в течении дня-двух. 
Я бы добавил в себе закладки поиск новых картинок с конца в место того, чтобы каждый раз искать конец новых картинок.

**Comment by 7nik** [comment]
У нас на сайте есть сверху: За последние 24 часа 107 принятых картинок. Новых картинок: 570. Готово к публикации: 26. Может стоит их сделать активными? нажимаешь на 570 - открываются все новые  - 9 страниц. Ни чего лишнего. Тыкаешь готовые к публикации - 26 - только прешки. Возможно любителям или желающим протегирировать было бы проще © blackbloodoff

**Comment by MiTereKun** [comment]
> Обычным пользователям не удобно искать прешки затесавшиеся между опубликованными, как результат на прешках теги могут появится только в течении дня-двух.

Я часто с телефона сидел, сохранял скриншоты картинок pre, потом дома ставил им теги (с телефона, понятое дело, даже с bluetooth клавиатурой - это сложно). Хоть и мобильная версия сайта весьма неплохая. Там можно было вообще этот блок выпилить, на планшетах хорошо встаёт ПК версия. Почему не кто у Гудвина внимательности не просил. Очень редко натыкался на картинки, где теги уже проставлены, потом стали ставить, а летом, с ссылкой - стало капитально всё в порядке, [Chimamire](https://anime-pictures.net/profile/view_ext_profile/97852?lang=ru) рос как а дрожжах) Его догонял [Максим](https://anime-pictures.net/profile/view_ext_profile/57122?lang=ru). Хотя гонкой это нельзя называть, но я стараюсь не лошить, честно, я не специально, я правда не замечаю

Хорошо, что через счётчик сделали. Получилось воскрешение Тег Ми, и оно довольно удобное. Даже понимаю, почему не подчеркнули строчку как ссылку⬏

**Comment by iDolmatov** [comment]
Тема точно должна быть открытой?
Не пойму, что сейчас ожидается от этой темы.

**Comment by 7nik** [comment]
>  поиск новых картинок с конца

хотя я сейчас не публикую картинки, так что, лично мне, это не особо критично, но было бы удобно остальным, я так думаю.

**Comment by iDolmatov** [comment]
Увы. Суть так и не понял.
Если ставить теги, то есть раздел "Предварительные картинки" и на странице пользователя они вначале. 
Во всех картинках PRE не вижу, а поиском по тегу отображаются. 
Сортировать в разделе PRE картинки в обратном порядке? Вроде сейчас логично, что новые вверху, а старые могут быть с тегами. Если нужно, то сортируешь по количеству тегов.
Но, мне кажется, что это я всё не то имею ввиду.

**Comment by 7nik** [comment]
Проверяются и публикуются картинки начиная с самых "старых" новых картинок. Т.е. надо открыть раздел Все картинки пролистать - сегодня (для моих 100 шт/стр) это 5ая страница, завтра это может быть 6ая или 4ая, а может останется 5ая.
В принципе, да, можно просто выставлять сортировку по обратной дате и тогда самые "старые" новые картинки будут идти на первой странице стразу после прешек.

**Comment by stalkerg** [comment]
Сейчас можно нажать с верху на цыфру с колличеством готовых к публикации картинок.

**Comment by 7nik** [comment]
Новых? Это же только для прешек сделано, а сейчас речь по новые картинки.
