### ISSUE TITLE
Фильтр проверки дублирования тегов пропускает некоторые теги

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#100]
Заметил, что теги V и L можно рекомендовать несколько раз.
Похоже, действует только для односимвольных тегов с алиасом.
![l](https://user-images.githubusercontent.com/19782385/71548735-699e2980-29d4-11ea-81e0-6d1f2377d0e4.png)
![v](https://user-images.githubusercontent.com/19782385/71548736-699e2980-29d4-11ea-86cf-c36c55290269.png)

**Comment by stalkerg** [comment]
звучит реально как баг, как будет время - сразу поправлю, спасибо!

**Comment by 7nik** [comment]
Любой алиас можно рекомендовать сколько угодно раз т.к. при рекомендации алиас заменяется на алиасируемый тег, а проверка показывает, что алиас и алиасируемый тег это разные теги и можно опять его рекомендовать.

**Comment by stalkerg** [comment]
Поправил, можете проверить?

**Comment by iDolmatov** [comment]
Повторить не удалось, значит исправлено.
