### ISSUE TITLE
Показ ошибки при добавлении в связку несуществующего ID

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#110]
Необходимо проверить/реализовать показ уведомления, когда ID не существует.
Примеры:
Указываем 0, пересылает на https://anime-pictures.net/pictures/add_rel_to_post/... с текстом 

> {"success":false,"errormsg":"Картинка с этим id не существует"}

Указываем 99999999999, пересылает на https://anime-pictures.net/pictures/add_rel_to_post/... с текстом 

> 500: Internal Server Error

В обоих случаях должен быть ответ без пересылки на другую страницу. 
Дополнительно можно писать введённый текст справа от кнопки добавления, как сделано для несуществующих тегов.

**Comment by 7nik** [comment]
Этим же страдают и несколько других таких же полей. Более того, туда можно ввести даже просто текст. Поле надо бы сделать `type="number" min="1"`.

> 99999999999

Негоже такие числа пихать в int.

**Comment by stalkerg** [comment]
> Негоже такие числа пихать в int.

Ну в Python это не страшно т.к. он в этом случае использует нумерики и там сколько угодно может быть. (почти)

**Comment by stalkerg** [comment]
Поправил. С точки зрения UI это отдельный разговор.
