### ISSUE TITLE
Убрать обновление страницы нажатием кнопки вопроса

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#112]
У справочного элемента ? есть пустой href и из-за этого нажатие на него вызывает обновление страницы. 
Предлагаю заменить его на **style="cursor: help;"**.

Таким образом будет понятно, что достаточно навести курсор для прочтения подсказки, а также избавит от ложной предпосылки нажать иконку для получения справки и не будет повторно открываться текущая страница.

**Comment by stalkerg** [comment]
Thanks, fixed.

**Comment by iDolmatov** [comment]
Ещё осталась подсказка у заголовка "Теги" и у заголовка "Параметры поиска".
