### ISSUE TITLE
Превью кода YouTube выходит за границы поля комментария

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#115]
Из-за большого превью видео нет возможности посмотреть и открыть картинку, связанную с комментарием. 
![image](https://user-images.githubusercontent.com/19782385/75597196-e4a7bd00-5ab5-11ea-9e4f-679e0d25fe7c.png)
Аналогично не учитываются границы при масштабировании, включая мобильную версию
![image](https://user-images.githubusercontent.com/19782385/75597332-b8407080-5ab6-11ea-8a24-e173d11cac95.png)
![image](https://user-images.githubusercontent.com/19782385/75597344-c55d5f80-5ab6-11ea-8404-e391720b667e.png)

____
Как понимаю, проблема из-за фиксированных height и width для div class="youtube-frame".
Проверил разные варианты и самым оптимальным вижу добавление в second.css для значений youtube-frame параметра: max-width: -webkit-fill-available;
При сохранении параметров ширины и высоты в различных тестовых вариантах не увидел проблем с правильным масштабированием на разных страницах: главная, страница комментариев, страница картинки.
Т.е. добавление этого параметра сохраняет отображение видео заданного размера при достаточном размере и уменьшает (вписывает) при недостаточном размере окружающего элемента.

**Comment by stalkerg** [comment]
Идея хорошая, хотя конечно очень специфично.
https://caniuse.com/#search=fill-available

Сейчас сделаю.

**Comment by stalkerg** [comment]
Спасибо - поправил.

**Comment by iDolmatov** [comment]
Что-то перемудрил, конфликты и растягивание на всю ширину получилось.
![image](https://user-images.githubusercontent.com/19782385/75600130-8ab2f180-5acd-11ea-9562-62dab3920dac.png)
Я предлагал другое свойство использовать, тогда получается так:
![image](https://user-images.githubusercontent.com/19782385/75600144-b3d38200-5acd-11ea-831b-47f402de9fd6.png)
![image](https://user-images.githubusercontent.com/19782385/75600155-cbab0600-5acd-11ea-82b4-2008cfc88acd.png)

**Comment by stalkerg** [comment]
можно было и без скриншотов :) поправил - копипаста зло.

**Comment by iDolmatov** [comment]
Спасибо. Думаю, теперь будет как надо.

Хотел предложить для картинок в комментариях такое же сделать, но, как вижу, там это уже ненужно.

**Comment by stalkerg** [comment]
Да, эти стили сквозные для bbcode
