### ISSUE TITLE
Раздел Аниме девушки (Anime girls/etc.)

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#116]
Полагаю, необходимо сделать английский вариант перевода для других языков, либо оптимизировать сам раздел.
Думаю, на многоязычном сайте лучше использовать английский язык при отсутствии перевода на выбранном языке, как сделано для других частей сайта.
___
Про вторую часть с оптимизацией раздела.
Сам я не использую данный раздел, т.к. привык пользоваться другими вариантами поиска картинок. Если раздел будет удобнее для поиска картинок, то есть шанс в увеличении его популярности.
Первое, что отталкивает - большое описание и пустое место. При моём разрешении экрана отображается всего две картинки с текстом посередине экрана. Это отталкивает, т.к. на сайте картинок в первую очередь ожидаешь увидеть картинки, а не книги.
Второй - восемь (почти девять) тысяч страниц. Многие ли будут просматривать столько страниц? Ответ стремится к нулю.

Переход к новому варианту.
На странице https://anime-pictures.net/pictures/anime_girls/ делаем заголовок по аналогии с названием тега при поиске по нему, только стиль другой. Под ним описание на всю ширину страницы. 
Желательно, краткое описание и кнопку-спойлер полного описания. Можно даже сделать на основе "Описание тегов" со страницы картинки, т.е. в заголовке "Аниме девушки - Все аниме девушки нашего сайта в одном месте", а под спойлером описание. 

Ниже картинки на всю ширину страницы, как сделано при просмотре всех картинок. 
Думаю, можно на странице вывести в зависимость от настройки пользователя "Количество элементов на страницу", даже с добавлением галочки "Включая страницу Аниме девушки" (без неё показываем, допустим, только 20 картинок на странице).

Справа можно добавить параметры поиска, которые фильтруют содержимое только этого раздела.
Полагаю, для этого раздела ненужны дополнительные условия поиска, но убирать их как-то сомнительно. Можно оставить поиск по тегам и сортировку, а остальное под дополнительным, т.е. сортировка позволит девушек за больший промежуток времени простым изменением порядка сортировки без дополнительного клика.

При открытии картинки должна сохранятся возможность листать картинки из открытого каталога.
Т.е. аналог просмотра картинок после перехода со страницы тега.

**Comment by stalkerg** [comment]
Назначение этой страницы - SEO оптимизация. В целом мы ее можем просто убрать.
