### ISSUE TITLE
Стиль страниц тегов и последних звёзд

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#120]
Как-то пустовато стало:
![image](https://user-images.githubusercontent.com/19782385/79124782-7e9d9d80-7db6-11ea-99e9-508b61bac923.png)
![image](https://user-images.githubusercontent.com/19782385/79124801-89583280-7db6-11ea-98cd-b4d8a3c06e36.png)

![image](https://user-images.githubusercontent.com/19782385/79124960-c7555680-7db6-11ea-863d-9bebd35ba516.png)

**Comment by MiTereKun** [comment]
это 100% временная ошибка. Слетел стиль так же на странице последних звёзд
[Вот так для страницы тегов](https://github.com/stalkerg/anime-pictures/issues/65#issuecomment-373609590) было бы конечно получше

**Comment by iDolmatov** [comment]
Почему-то думал, что там было время. Может невнимательно смотрел.

**Comment by stalkerg** [comment]
Уууупс, сейчас гляну.

**Comment by stalkerg** [comment]
Исправил, спасибо. Последнее обновление было крайне крупным и затронуло много всего.
