### ISSUE TITLE
Редизайн

### ISSUE THREAD

**Issue by ostiwe** [stalkerg/anime-pictures#128]
Предлагаю сделать редизайн сайта, так как он уже визуально устарел. 

**Готов помочь/сделать редизайн**. Для примера, я сделал набросок того, как я представляю себе переделанный сайт.

Ниже скриншоты работы.

Разумеется это **не окончательная версия**, если меня поддержат достаточное количество людей или администрация сайта, я продолжу разработку, **как клиентской так и серверной части (если будет необходимо)**

<img width="1220" alt="Снимок экрана 2020-07-30 в 18 43 24" src="https://user-images.githubusercontent.com/60335090/88944111-02f82b80-d295-11ea-93fb-ca94aaad0bda.png">
<img width="1219" alt="Снимок экрана 2020-07-30 в 18 43 35" src="https://user-images.githubusercontent.com/60335090/88944129-0986a300-d295-11ea-9abd-bb201d14a8f0.png">
<img width="1221" alt="Снимок экрана 2020-07-30 в 18 43 47" src="https://user-images.githubusercontent.com/60335090/88944135-0ab7d000-d295-11ea-8421-d7aee5c87dbf.png">
<img width="1221" alt="Снимок экрана 2020-07-30 в 18 44 13" src="https://user-images.githubusercontent.com/60335090/88944141-0b506680-d295-11ea-832f-1742f60e9848.png">
<img width="1219" alt="Снимок экрана 2020-07-30 в 18 44 22" src="https://user-images.githubusercontent.com/60335090/88944147-0c819380-d295-11ea-8864-6d2cc695f824.png">

**Comment by stalkerg** [comment]
1.  С чего вы решили что он устарел?
2. Функционал вашего дизайна мягко говоря не дотягивает. Попытайтесь добавить всю ту информацию что выводим мы и у вас получится близко к тому что есть.

**Comment by ostiwe** [comment]
> 1.  С чего вы решили что он устарел?
> 
> 2. Функционал вашего дизайна мягко говоря не дотягивает. Попытайтесь добавить всю ту информацию что выводим мы и у вас получится близко к тому что есть. 



1. Это решение обосновано тем, что по моему мнению, он не соответствует текущему времени. Выглядит как пережиток прошлого.
2. (На скринах рабочий "сайт") Конечно не дотягивает, делалось на "скорую" руку, если так можно выразиться. И это "черновой" вариант, далее много чего изменится. 

Хотя может он и не "пережиток" а просто немного неудачный, так как в некоторых местах он перегружен странной информацией. 




Этот ответ можно посчитать достаточно грубым, особенно ответ на 1 вопрос, если каким-либо образом задел - приношу извинения, ибо понимаю, что в текущую версию сайта вложено много сил.

**Comment by stalkerg** [comment]
Это не грубый ответ но не очень информативный. Попробуйте сформулировать что именно вам кажется не соответствует текущему времени и какая именно информация лежит "неумело". 
Хочется общаться предметно а не в формате "я люблю наруто а я люблю блич".

**Comment by ostiwe** [comment]
###### Получилось что-то вроде критики, так что заранее прошу извинить если что. 

По поводу того, что сайт не соответствует времени - возможно только я так думаю. Просто когда я захожу на сайт, то у меня появляется такое ощущение, что я в 2005-2009 году. Ибо все выглядит так, что после создании этой версии сайта на него просто забили в плане глобальных изменений, и просто добавляют что-то, что захламляет весь сайт. 


К примеру, на главной страницы мы видим

- Последние добавленные картинки
- Последние сообщения из чата
- Популярные картинки за день
- Популярные за неделю
- Топ пользователей
- Последние комментарии
- Топ модераторов

Как по мне блоки с чатом, комментариями, топами (всего) на главной странице - лишнее. 
По моему мнению было бы лучше там оставить только блоки связанные с картинками, так как это основная тематика сайта. 

Далее, если последние сообщения из чата так важны, его (весь чат) вообще можно вынести сайд-бар с возможностью его раскрыть и присоединиться к нему, или же просто смотреть сообщения. 

-------------

Теперь перейдем к сайд-бару. 

Логику входа и прочего связанного с профилем можно вынести в шапку чтобы не мешалась, так же сделать с изменением темой и языка в шапке.

Строку поиска на самый верх сайд-бара. 

Блок "Последние звёзды" лучше вынести на главную страницу с названием "Набирают популярность" к примеру. 

Ссылки на приложения, социальные сети как по мне лучше переместить в подвал, так же с ссылкой на патрон. 

-------------

На странице с артом, много не нужной информации как по мне. 

К примеру, зачем пользователю знат следующее:

* Дата загрузки
* Цвет
* Артефактность
* Размытие
* Общий (вообще не понятно что это)

Также на странице с атром есть qr код в сайд-баре, что тоже как по мне лишнее. 
Его можно вынести в меню "поделиться", где будут и другие ссылки для обена данной страницой (например код для вставки на другой сайт, показать qr код и т.п.).

Блок "Похожа на" можно не показывать, а сделать как ссылкой в каком-нибудь месте с названием "Показать похожие картинки". 

Блок "Избранное для" тоже как по мне лишнее, можно просто показывать количество людей, которые добавили в избранное. 

Блок в сайд-баре "сейчас смотрят" тоже не понятно зачем там расположен, лишнее место занимает, можно было бы просто где-нибудь разместить что-то похожее "Сейчас смотрят: 121 человек"

-------------

Далее страница с обзором [картинок](https://anime-pictures.net/pictures/view_posts/0?lang=ru)

Сетку картинок можно сделать как на Pinterest, так будет лучше выглядеть. 

Информация о разрешении картинки как по мне лишнее, лучше акцентировать внимание на самих картинках.

В низу страницы между пагинацией и быстрым переходом к странице есть непонятный текст по типу "31.07.20, 17:36 - 31.07.20, 7:30". Почему не понятный - никакого намека на что это нет, лучше написать что это значит, либо вообще убрать.

**Comment by ostiwe** [comment]
Кстати, немного отходя от темы - при загрузке картинок иногда появляются дубликаты (с одним и тем же ID)

**Comment by 7nik** [comment]
Отмечу, что все ваши замечания весомы только для пользователей просматривающих/скачивающих картинки. При этом вы игнорируете потребности пользователей загружающих и тегирующих картинки, а также модераторов.

> Ссылки на приложения, социальные сети как по мне лучше переместить в подвал, так же с ссылкой на патрон.

Error 404, подвал not found.

Дата загрузки нужна бывает при модерации, хотя сейчас и не так сильно как раньше, когда не было очереди на проверку.

Блоку "Похоже на" я себе сделал свёрнутым по-умолчанию.

Блок "Сейчас смотрят" нужен чтобы несколько людей, а особенно модераторов, не пытались одновременно тегировать/проверять одну и туже картинку.

> Информация о разрешении картинки как по мне лишнее

Это ваше мнения, а у меня, например, есть отдельный пункт связаный с разрешением, и меня не прельстит мысль открывать все картинки просто чтобы узнать их разрешение.

> "31.07.20, 17:36 - 31.07.20, 7:30" 

Да что тут не понятного то? Это диапозон дат публикации отображаемых картинок.
Это вы ещё не знаете как узнать кто добавил на картинку какой-либо тег)))

<HR>

Вообще, прежде чем выкидывать или реарганизовывать какую-либо информацию, нужно сначала выяснить её раельную значимомть, и не методом "а мне так кажется", а анализом статистики (но это только к сталку) или проведением опросов пользователей о том знают ли они о функции Х и как часто пользуются ею и уже затем думать нужна ли эта информация и где она должна быть расположена.

P.S.: Вот, например, как я подправил дизайн и одной из целей было избавиться от скролинга при модерировании:
![image](https://user-images.githubusercontent.com/29704098/89052099-e116ab80-d35d-11ea-95c1-12b1951f6383.png)

**Comment by ostiwe** [comment]
> Отмечу, что все ваши замечания весомы только для пользователей просматривающих/скачивающих картинки. При этом вы игнорируете потребности пользователей загружающих и тегирующих картинки, а также модераторов.

Так и есть, упор в основном на обычного пользователя. 

Для админов/модераторов было бы неплохо сделать админку, где будут все необходимые им инструменты. Таким образом можно даже немного упростить им работу, так как в админке будет чисто "рабочий" интерфейс. 

----
>
>>Информация о разрешении картинки как по мне лишнее
>
> Это ваше мнения, а у меня, например, есть отдельный пункт связаный с разрешением, и меня не прельстит мысль открывать все картинки просто чтобы узнать их разрешение.

Эту информацию можно показывать при наведении, как пример.

**Comment by stalkerg** [comment]
@ostiwe  Так, стоп. Вы начали с того что 
> Предлагаю сделать редизайн сайта, так как он уже визуально устарел.

Но вся ваша критика относится не к дизайну а скорее к сути сайта - той информации которую мы показываем и где при этом никакой критики "визуальной" составляющей я так и не нашел. Хотя честно говоря хотел бы услышать. 

> Ибо все выглядит так, что после создании этой версии сайта на него просто забили в плане глобальных изменений, и просто добавляют что-то, что захламляет весь сайт.

Для frontend это отчасти верно но вот бекенд был переписан с 0 полностью и это заняло 3 года. Подготовка к переделке frontend начата и даже процентов на 60 закончена (не просто так пропал footer и некоторые части сайта перешли на svelte).

В целом захламление есть и мы будем делать редизайн но его главное условие - не ухудшить функционал. 
> Для админов/модераторов было бы неплохо сделать админку, где будут все необходимые им инструменты. Таким образом можно даже немного упростить им работу, так как в админке будет чисто "рабочий" интерфейс.

Это нереально и не имеет смысла так как модераторский интерфейс на 90% совпадает с обычным. Кроме того вы забыли обычных пользователей но тех кто заливает картинки. Админка хороша когда интерфейс или абстракция с которой он должен работать сильно отличается от того с чем работает обычный пользователь и это не наш случай.

**Comment by stalkerg** [comment]
> Блок "Последние звёзды" лучше вынести на главную страницу с названием "Набирают популярность" к примеру.

это не просто последние звезды... они по websocket в реальном времени обновляются именно по этому этот блок сквозной для всех страниц.

**Comment by ostiwe** [comment]
>Это нереально и не имеет смысла так как модераторский интерфейс на 90% совпадает с обычным. Кроме того вы забыли обычных пользователей но тех кто заливает картинки. Админка хороша когда интерфейс или абстракция с которой он должен работать сильно отличается от того с чем работает обычный пользователь и это не наш случай.


Тогда в данном случае можно хотя бы скрыть от обычных пользователей информацию, которая им по-сути не нужна

**Comment by stalkerg** [comment]
> На странице с артом, много не нужной информации как по мне.

Понимаете удалить информацию и получить красивую картинку очень легко но искусство именно в том что бы показать всю необходимую информацию и при этом не перегрузить пользователя.

**Comment by ostiwe** [comment]
>это не просто последние звезды... они по websocket в реальном времени обновляются именно по этому этот блок сквозной для всех страниц.

Честно говоря не особо понятен его смысл (в плане зачем его вообще выносить в сайдбар)

**Comment by stalkerg** [comment]
> Честно говоря не особо понятен его смысл (в плане зачем его вообще выносить в сайдбар)

Простите за нескромный вопрос - сколько у вас лет опыта в веб дизайне? Или в веб разработке в целом? Это не наезд если что или что то типо того.

**Comment by ostiwe** [comment]
> Простите за нескромный вопрос - сколько у вас лет опыта в веб дизайне? Или в веб разработке в целом? Это не наезд если что или что то типо того.

Вообще я по большей части бекендом занимаюсь, уже как 3-4 года вроде, но в силу обстоятельств мне приходиться делать то и другое. 

Что касается дизайна - я не силен в этом поэтому в основном я делаю интерфейсы которые я посчитаю красивыми и функциональными по моему мнению. И создавая данную тему я скорее выступал как обычный пользователь. 

В любом случае - я открыт для любой критики, ну, если что.

**Comment by stalkerg** [comment]
> Сетку картинок можно сделать как на Pinterest, так будет лучше выглядеть.

Это не работает с пагинацией и в ней непонятен порядок картинок. (во многих случаях это важно)

**Comment by ostiwe** [comment]
> Что касается дизайна - я не силен в этом поэтому в основном я делаю интерфейсы которые я посчитаю красивыми и функциональными по моему мнению. И создавая данную тему я скорее выступал как обычный пользователь.


Так что, я не буду удивлен если из-за этого может появится какой-либо негатив. 


Да и в целом, если бы я знал всю логику "приложения" было бы проще вести диалог.

**Comment by ostiwe** [comment]
> Это не работает с пагинацией и в ней непонятен порядок картинок. (во многих случаях это важно)

Не понятен для пользователей?

Просто к примеру это может выглядеть так
![screencapture-localhost-3000-test-2020-08-01-18_11_04](https://user-images.githubusercontent.com/60335090/89104499-78ddcd80-d422-11ea-82d7-d73a93144590.png)

**Comment by stalkerg** [comment]
1. Давайте по порядку -  у вас претензия не к дизайну а к layout. 
2. И да, попробуйте заливать картинки, тегировать и дождаться проверки модератором. Думаю немного больше поймете логику сайта. 
3. Наш сайт не просто для того что бы пользователи залипали в картинки, а скорее для организации крупной и семантически связанной коллекции картинок что то ближе к википедии но с более сложным поиском на основе тегов. Отсюда и пагинация вместо бесконечного скрола и многие другие отличия от пинтерест подобных сайтов. Если вы посмотрите на наших конкурентов то там ситуация +- похожая (и да, наш конкурент не пинтерест)
4. Я в индустрии больше 15 лет и процентов 30% времени занимался frontend причем не только web. То как вы сейчас воспринимаете сайт и то как вы думаете что его воспринимают люди - нормально в вашей ситуации но это очень поверхностно не говоря уж о том что вы не видите сторону модераторов и заливальщиков. 

Теперь немного реализма
Вы не сможете сейчас сделать новый layout и дизайн всех блоков включая модераторский функционал за разумное время, и я не смогу. 
Именно по этому я готовлю сайт к тому что бы страницу за страницей переводить на Svelte и менять понемногу layout и дизайн. После чего можно было бы внедрять новые фичи и пересматривать старые. (сейчас это сложно)
План сейчас такой (включает небольшие оптимизации на каждом из этапов)
1. Подготовка к постраничной переписыванию сайта. 
2. Постраничное переписывание на Svelte и может быть Sapper.
3. Любые другие преобразования включая сам дизайн.

**Comment by stalkerg** [comment]
> Просто к примеру это может выглядеть так

Именно, я совсем не ожидал увидеть 5 и я ожидал там 4. Опять же в этом случае у вас с низу криво лежат куски. Кроме того фишка сайта в том что картинки обрамлены их средним цветом с указанием разрешения.

**Comment by ostiwe** [comment]
Что ж, тогда думаю можно закрывать эту тему. 

Просто хотелось бы, как рядовому пользователю видеть перед собой приятный интерфейс. 

Благодарен за ответы и удачи с сайтом.

**Comment by MiTereKun** [comment]
>пагинация в Pinterest Не понятна для пользователей?

у облака майла, сначала в приложении, а потом и в вебе несколько месяцев продержалась именно такая сетка. Её убрали, и не исключено, что под шквалом критики. По тому что сервис больше рабочий, чем просто галерея. Кроме пинтереста и mywaifulist её ни где не видел, так как она неудобная.

Я не сильно разбираюсь в дизайне, но от описанного вами в [5-том сообщении](https://github.com/stalkerg/anime-pictures/issues/128#issuecomment-667165374) немного побледнел. Ну хотя бы про блоки "похоже картинки" и "последние звёзды": обычным пользователям они позволяют продолжить навигацию по сайту без лишних движений, как и механизм редиректа с забаненной картинки или пользователя на страницу поиска.

Чат в сайд-бар просто не вместиться! Если уж и выносить, то внизу иконку с разворачивающемся чатом, как на различных сайтах из конструкторов "напишите нам". Но это бред и будет только отвлекать от контента. А вот развёрнутый блок "последние звёзды" в сайд-баре это удобно.

>Блоки "Избранное для" и "сейчас смотрят" сделать численными

Что плохого в открытости и точности? И опять же, это всё позволяет находить картинки самыми разными методами и продолжать навигацию в любом случаи.

Ну а "разрешение" картинки это показатель её качества, для поисковика сильно важный параметр, который должен быть на самих страницах поисковой выдачи

**Comment by MiTereKun** [comment]
<details> 
<summary>Вот так дизайн страницы картинки изменился с 2017 на сегодняшний</summary>
<img src="https://user-images.githubusercontent.com/32958490/89114856-3ff63500-d4c4-11ea-912d-9f2f5fccc2a8.PNG" alt="">
</details>
<details> 
<summary>Теги стали удобнее и приобрели современный вид.</summary>
<img src="https://user-images.githubusercontent.com/32958490/89114921-d165a700-d4c4-11ea-9add-9cdcf128dd54.png" alt="">
</details>

Но убрать из них количество картинок и расположить по 2 в ряд забивая на категории - будет бессмысленно и для пользователей, и для модераторов.

**Comment by MiTereKun** [comment]
<details> 
<summary>Вот так дизайн страницы картинки изменился с 2017 на сегодняшний</summary>
<img src="https://user-images.githubusercontent.com/32958490/89114856-3ff63500-d4c4-11ea-912d-9f2f5fccc2a8.PNG" alt="">
</details>
<details> 
<summary>Теги стали удобнее и приобрели современный вид.</summary>
<img src="https://user-images.githubusercontent.com/32958490/89114921-d165a700-d4c4-11ea-9add-9cdcf128dd54.png" alt="">
</details>

Но убрать из них количество картинок и расположить по 2 в ряд забивая на категории - будет бессмысленно и для пользователей, и для модераторов.

<details> 
<summary>Кстати так было в 12-том году по макету пиксива (и на нём так и осталось)</summary>
<img src="https://sun9-67.userapi.com/c9830/u101463827/-14/w_9a4f3941.jpg" alt="">
</details>

Но сейчас это невозможно, так как количество тегов сильно вросло.

<details> 
  <summary>Не хотелось бы получить вариант редизайна санкаку</summary>
<img src="https://user-images.githubusercontent.com/32958490/89115584-4e951a00-d4cd-11ea-9f7f-ebb7fbb1aca1.png" alt="">
</details>

На мониторе персонального компьютера все элементы выглядят сильно крупными. Вкладка Resolution какое-то издевательство. Просто клик по картинки куда лучше (в редизайне этот метод отключён). Не пользуюсь этой бурой

**Comment by stalkerg** [comment]
>Просто хотелось бы, как рядовому пользователю видеть перед собой приятный интерфейс.

Мы бы то же хотели видеть приятный интерфейс. Но как я сказал выше вы предложили много разных идей связанных со сменой компоновки (layout) сайта при этом без учета разных типов пользователей. 
Если вы предложите более взвешенные изменения причем не все разом а маленькими порциями то мы можем обсуждать и внедрять их по отдельности. 
Часть того что вы сказали я и сам хочу внедрить.
