### ISSUE TITLE
Параметр outline-offset для строки поиска

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#129]
Просьба убрать outline-offset или установить положительное значение.
Сейчас отрицательное значение "съедает" буквы в Google Chrome:
![image](https://user-images.githubusercontent.com/19782385/89907854-9ec75700-dc06-11ea-8d6a-d323195e02cf.png)
Без этого параметра читаемо:
![image](https://user-images.githubusercontent.com/19782385/89908048-df26d500-dc06-11ea-9a24-dc021edba74b.png)
С положительным значением:
![image](https://user-images.githubusercontent.com/19782385/89908213-0c738300-dc07-11ea-972f-510bea752952.png)

В Firefox такой бяки не замечено.

**Comment by stalkerg** [comment]
Спасибо! Поправлю. Это кажись новая выдумка Хрома в новых версиях.

**Comment by stalkerg** [comment]
Пофиксил.
