### ISSUE TITLE
Автор при запросе json

### ISSUE THREAD

**Issue by ostiwe** [stalkerg/anime-pictures#134]
При запросе данного вида:
`https://anime-pictures.net/pictures/view_post/675450?lang=ru&type=json`

Возвращается следующий объект
```
{
    "id": 675450,
    "md5": "ce5bcb21ae1881e08e2d180a5e586588",
    "md5_pixels": "beda7bb7f4812b24983594fd37e1fd2b",
    "width": 1131,
    "height": 1600,
    "small_preview": "https://ip1.anime-pictures.net/previews/ce5/ce5bcb21ae1881e08e2d180a5e586588_sp.jpg.webp",
    "medium_preview": "https://ip1.anime-pictures.net/previews/ce5/ce5bcb21ae1881e08e2d180a5e586588_cp.jpg.webp",
    "big_preview": "https://ip1.anime-pictures.net/previews/ce5/ce5bcb21ae1881e08e2d180a5e586588_bp.jpg.webp",
    "pubtime": "2020-11-18 14:47:20.684892",
    "score": 0,
    "score_number": 14,
    "size": 773579,
    "download_count": 35,
    "erotics": 0,
    "color": [
        123,
        111,
        116
    ],
    "ext": ".jpeg",
    "status": 1,
    "spoiler": false,
    "have_alpha": false,
    "user_name": "ᴊᴏɴ",
    "user_id": 211021,
    "user_avatar": "/static/avatars/211/211021.png",
    "tags": [
        "оригинальное изображение",
        "koh rd",
        "один (одна)",
        "высокое изображение",
        "румянец",
        "смотрит на зрителя",
       ....
    ],
    "tags_full": [
        {
            "name": "оригинальное изображение",
            "type": 6,
            "num": 125077
        },
        {
            "name": "koh rd",
            "type": 4,
            "num": 61
        },
       ....
    ],
    "file_url": "https://anime-pictures.net/pictures/get_image/675450-1131x1600-original-koh rd-single-tall image-blush-looking at viewer.jpeg"
}
```

Сюда можно как-нибудь вывести автора изображения?

Просто как-то странно, в веб-версии есть а в json`е нет.

**Comment by ostiwe** [comment]
Имеется ввиду, линк на автора или на изображение (pixiv, twitter и тд)

**Comment by 7nik** [comment]
Да там много чего нет такого, что есть в html версии.
Просто отфильтруйте теги с типом 4 (авторы) и запрашивайте инфу через `https://anime-pictures.net/api/v3/tags?tag:smart=koh%20rd`.
Вообще немного страно что в tags_full нет айди тегов)))

А ещё можно пользоваться `https://anime-pictures.net/api/v2/posts/675450/tags?lang=en`.

**Comment by ostiwe** [comment]
> Да там много чего нет такого, что есть в html версии.
> Просто отфильтруйте теги с типом 4 (атвторы) и запрашивайте инфу через `https://anime-pictures.net/api/v3/tags?tag:smart=koh%20rd`.
> 
> Вообще немного страно что в tags_full нет айди тегов)))

Эт лан, но мне собсна надо узнать линк на автора из поста. Т.е я запрашиваю страницу поста в виде json, и ожидаю там увидеть блок с информацией об авторе, или хотя бы ссылку на его твиттер, пиксив.

**Comment by ostiwe** [comment]
Последняя ссылка не робит, 400 выкидывает

**Comment by 7nik** [comment]
Залогинится для неё надо.

**Comment by stalkerg** [comment]
У нас нету концепции автора картинки, у нас есть только теги. (тем более авторов может быть много)

**Comment by ostiwe** [comment]
Снова привет, а возможность получать посты через ?type=json закрыли?

**Comment by 7nik** [comment]
Если добавить `lang` параметр, оно работает?

А вообще есть альтернатива: https://anime-pictures.net/api/v3/posts/675450 - там правда структура немного другая, зато данных больше.
Там уже для примерно всего есть /api/v3/* ендпоинты.

**Comment by ostiwe** [comment]
Круто, а есть возможность где-то посмотреть список роутов? 
Просто, если к примеру запросить https://anime-pictures.net/api/v3/posts - делает редирект на веб-версию.

> Если добавить lang параметр, оно работает?

Нет

**Comment by stalkerg** [comment]
> Снова привет, а возможность получать посты через ?type=json закрыли?

https://anime-pictures.net/pictures/view_posts/0?lang=ru&type=json работает

**Comment by ostiwe** [comment]
Хм, и правда, из-за языка. Спасибо

**Comment by 7nik** [comment]
> Круто, а есть возможность где-то посмотреть список роутов?

Вроде ещё нет публичного списка с описание, но планировался.
Так что можно просто походить по сайту и посмотреть куда какие запросы делаются.
Или спросить чего конкретного хочется.

**Comment by stalkerg** [comment]
`/api/v3/posts` пока ещё не доконца честный т.к. шарит код с view_posts по сему есть некоторые странности в поведении.
В целом и по старому endpoint можно добится такого же поведения - `https://anime-pictures.net/pictures/view_posts/0?lang=ru&type=json_v3`
