### ISSUE TITLE
Недоступная история чата

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#14]
Нельзя просмотреть историю чата. Для не частых гостей бывает весьма актуально.

**Comment by iDolmatov** [comment]
Реализовано в новой версии чата: сообщения подгружаются постепенно и можно посмотреть сообщения за последние девять лет.

**Comment by stalkerg** [comment]
Я думал еще сделать возможность смотреть в прошлое "сразу" без занудной промотки. 
Но если это не нужно то могу закрыть issue.

**Comment by iDolmatov** [comment]
По мне и так нормально, т.к. сомнительно, что многие захотят читать большую историю. 
Я даже автоматизировал это действие, т.к. без движения мыши браузер отказывался прокручивать сообщения спустя несколько прокруток и это занимало много времени.

По идее, можно было бы реализовать фильтр-календарь по аналогии с Пикабу, но непонятно куда его лаконично вписать в чат. 
Однако, между BB-кодами и кнопками отправки мало места при минимальном размере, а справа только над именами пользователей размещать. Иметь сдвиг основной части чата вообще бы не хотелось.
Приемлемую вижу только идею размещения кнопки в футтере чате под именами пользователей наравне с нижней границей сообщений в виде кнопки всей истории чата на отдельной странице или отдельным файлом.
