### ISSUE TITLE
Функция поиска ранее введенных тегов в поле для добавления тегов

### ISSUE THREAD

**Issue by MiTereKun** [stalkerg/anime-pictures#145]
**суть**™

![Безымянный-1](https://user-images.githubusercontent.com/32958490/181578382-28f3575f-74ba-480e-990a-bc2d9fa16afc.png)

**Пример работы:**
 <p><img src="https://user-images.githubusercontent.com/32958490/181578699-1389a920-2194-444a-937d-c5a30d9cc45b.png" width="220" alt=""></p>

Серый не активный элемент - это стандарт, символизирующий запрет на действие. В данном случаи означает, что тег уже поставлен.

Если пользователь или модератор всё же нажмёт сюда - введённая часть тега удалиться до последней конъюнкции. Или, если была введена только часть одного тега - поле отчиститься полностью.
Таким образом сайт станет более самодостаточным и даже станет удобнее при работе с устройств без физической клавиатуры.

**Comment by iDolmatov** [comment]
Заголовок правильный?
Идею про оптимизацию ввода тегов понял, а про удаление не понял.

**Comment by stalkerg** [comment]
ну т.е. ты хочешь отдельно маркировать те теги которые уже и так стоят? разумно! попробую сделать

**Comment by MiTereKun** [comment]
При вводе тегов в поле - появляется стандартные подсказки, но вписанные ранее теги там представлены в сером цвете. При нажатии на серый тег из подсказок - поле ввода тегов отчиститься до предыдущего (или до символа ||), так как теги обычно пишут сразу друг-за-другом.
Если справа у серого тега сделать иконку корзины и позволять удалять проставленные теги с самой картинки - это будет уже перегруз функционала,  ведь это всё же поле подсказок. Но мне и самому покаялось, что я именно это имел в виду под удалением

**Comment by iDolmatov** [comment]
> При вводе тегов в поле - появляется стандартные подсказки, но вписанные ранее теги там представлены в сером цвете.

Звучит так, что предлагаешь анализировать поле ввода тегов. Первый пост показывает. что нужно анализировать теги с картинки.
Это немного разные задачи. Для тегов на картинке ещё нужно учесть, что мы не показываем рекомендованные теги в реальном времени (не модераторам). Соответственно, нужно делать парсинг вводимого текста, тегов картинки и рекомендованных тегов.

Для парсинга строки по ещё не добавленным (*рекомендованным тегам) учитывайте, что пользователь может случайно не то нажать. Поэтому удаление текста наоборот замедлит ввод тегов. Учитывает набор мышь+клавиатура. Для сенсора и виртуальной клавиатуры зависит от устройства, порядка действий и т.п.
Например, набираю "карандаш". Хочу выбрать "юбка-карандаш", но выбираю "карандаш". Сейчас могу стереть "||" и выбрать другую подсказку. Нажатие бекспей два раза. Если реализовать удаление текста, то придётся снова набирать слово. Аналогично с "волосы". Могу два раза кликнуть лишнее слово и удалить его.
Конечно, зависит от навыков и привычек пользователя. Например, для одиночного ввода мне быстрее клавиатурой выбрать весь текст и снова набрать.

Обдумывал скрытие существующих тегов из рекомендаций. но пришёл к выводу не наглядности, словно тега не существует.
_________________
В итоге, пока пришёл к выводу, что не совсем понимаю какую задачу решает запрос на реализацию.

Исключить дублирование тегов в строке ввода?
Для картинок с правами установки тегов (своя новая или модератор) дубликаты тегов не вызывают ошибок.

Исключить ошибки "have already on picture", "have already in recommendation", "unknown tag"?
Реализовать очистку поля с показом ошибки. Принимать допустимые теги, остальные игнорировать. Поиск ошибок в строке часто занимает больше времени, чем заново набрать пару тегов. Особенно, учитывая малую ширину поля ввода. 
Копирования тегов с других сайтов нет. да и всё равно нужно проверять правильность тегов.
Если ошибок много, то реализовать кнопку (i) с логом уведомлений, которая появляется при показе уведомлений. Размещается рядом с кнопкой "Добавить". убирается при навигации/закрытии страницы.

Показывать, что тег уже есть на картинке?
Зачем тогда очищать поле? Сделайте уведомление сразу при вызове тега и не меняйте строку ввода в этот момент.
Уведомление о наличии тега будет работать. если использовалась копипаста или тег набран вручную без подсказки.

**Comment by stalkerg** [comment]
@iDolmatov Ми часто работает с сайтом с планшета или смартфона без физической клавы, ему ещё раз набирать текст значительно сложнее. И ты немного про другое говоришь. А так поле ввода и теги мы и так парсим.

**Comment by MiTereKun** [comment]
Большое спасибо за реализацию.
@iDolmatov, Идея тут не только в том, что бы облегчить работу с планшета, но и что бы в целом уменьшить время на тегирование и не запутаться лишний раз какие теги введены, а какие пропущены. А так же что бы исключить необходимости писать теги сначала в поле поиска на странице (по ctrl+F), а потом писать то же самое в поле ввода тегов (лично я так делаю очень часто).

> Первый пост показывает. что нужно анализировать теги с картинки.

Речь не про ИИ распознавание... Или что имелось в виду под "анализировать теги с картинки"?
Там просто изображено поле которые вызывается на ctrl+F и поле ввода тегов, по этому и изначальное название "Совмещение поля ввода тегов и поиска на странице браузера", типа эти 2 поля станут одним целым)

> набираю "карандаш". Хочу выбрать "юбка-карандаш", но выбираю "карандаш". Сейчас могу стереть "||" и выбрать другую подсказку

Правильно говоришь, так оно и работает после реализации. Зачёркнутый тег не тот который сейчас прописан через "||" (там дубли не важны), а только тот, который уже добавлен на картинку. Идея именно в этом и Stalkerg её правильно понял. Удаление при нажатии тоже просто чуть-чуть экономит время, так как пользователь мог думать именно про уже поставленный тег. Тут всё получилось классно

> Если ошибок много, то реализовать кнопку (i) с логом уведомлений, которая появляется при показе уведомлений. Размещается рядом с кнопкой "Добавить". убирается при навигации/закрытии страницы.

Да, сейчас если копировать - то приходиться скринштотить страницу, вписывать теги в notepad

<details>
<summary>и после искать ошибки по скрину</summary>
<img src="https://github.com/stalkerg/anime-pictures/assets/32958490/734fe3a1-d6d0-4962-ae44-6f602745f40a" alt="">
</details>

Можно сделать подобный лог. Но качество тегирвоания на booru в целом низкое, поэтому копирование немного бесполезно...

> Ми часто работает с сайтом с планшета или смартфона без физической клавы

@stalkerg, Это было бы хорошее объяснение от куда у меня так много ошибок но это увы совсем не так, я работаю всегда только с клавиатурой (но знаю людей которые работают с телефона).
Ошибки в тегах у меня по тому, что.... Когда я несколько лел подряд пытался делать всё без ошибок максимально подробно - ошибки все ровно были и в конце всё мотивировало, я зыбил вылизывать каждую детальку (тем более фоном идёт физическая работа), думаю, так далеко не только у меня было. И теперь спокойно в базовых тегах могу голубые глаза обозвать сними волосами, по тому что тега "синие глаза" нет... (конечно нужно быть как обычно внимательнее).

В целом базовый набор тегов самый коварный, его нужно ставить на вообще абсолютно каждую картинку и это реально задалбывает, писать одни и те же слова по 10 раз на дню. В 20 году когда занимался общественной работой со старыми пикчами - попросил @7nik написать список моих "постоянно рекомендуемых тегов", <details>
<summary>выглядело круто это выглядело</summary>
<img src="https://github.com/stalkerg/anime-pictures/assets/32958490/f81931be-aa1b-41e2-905e-88d8da6969a8" alt="">
</details>
Какое было моё удивление когда появилось ИИ распознавание тегов на booru и там это реализовали через
<br><br>

<details>

<summary>почти такие же галочки</summary>

<img src="https://github.com/stalkerg/anime-pictures/assets/32958490/ff10f80a-bb98-4e9b-b15d-ee7116bf6bbb" alt="">
</details>

Функция полезная и максимально поменяет подход ко всей работе тегирования

**Comment by MiTereKun** [comment]
<details>
<summary>Для истории - на данный момент у реализованный функции (в рамках изначальной идей) есть следующие недостатки:</summary>
<img src="https://github.com/stalkerg/anime-pictures/assets/32958490/599f0d6b-cb00-4302-85a3-821b989d5a51" alt="">
</details>

- ещё чуть-чуть медленнее стали открываться подсказки (уже пофиксили)
- работу с удалёнными тегами так же пофиксили

**Comment by stalkerg** [comment]
>  Какое было моё удивление когда появилось ИИ распознавание тегов на booru и там это реализовали через 

у меня есть прототип ИИ, но моей GPU не хватает что бы это тренировать до адекватного качества. Надо арендовывать сервера... пока тупо времени нет.

**Comment by iDolmatov** [comment]
С ии, в некоторой степени, пользователи не проверяют теги и не ставят другие. Нужно ещё думать, чтобы это работало в правильной реализации.
Я подразумевал не анализ картинки, а анализ проставленных тегов. Что сейчас частично реализовано. Жаль, что для чужих постов это не работает, чтобы не пытаться рекомендовать уже одобренные теги.
