### ISSUE TITLE
503 при запросе артов

### ISSUE THREAD

**Issue by ostiwe** [stalkerg/anime-pictures#148]
Привет, я правильно понимаю что есть рейт лимитер на ручки вида  https://anime-pictures.net/pictures/view_post/815358?lang=en&type=json_v3 ?

В связи с изменениями в поведении ручки https://anime-pictures.net/pictures/view_posts/1?lang=en&type=json_v3&posts_per_page=80 (из ответа убрали big_preview и тд), приходится проходиться по каждому арту по отдельности. 

Пытался это сделать в многопотоке, чтоб ускорить немного процесс, но уткнулся на данную проблему (503 при выполнении запроса по типу https://anime-pictures.net/pictures/view_post/815358?lang=en&type=json_v3

Или есть какой-то еще вариант?

**Comment by 7nik** [comment]
Так сылки собираються на основе инфы из поиска, что-то типа
```js
function getPreview (post, size) {
    const host = `//cdn.anime-pictures.net/previews/`;
    const name = `${post.md5.slice(0, 3)}/${post.md5}_`;
    const ext1 = post.ext === ".gif" ? ".gif" : post.have_alpha ? ".png" : ".jpg";
    const ext2 = post.ext === ".gif" ? ".webp" : ".avif";
    return [host, name, size, ext1, ext2].join("");
}
```
где `size` может быть `"sp"` (150px), `"cp"` (300px) и `"bp"` (600px). `ext2` не обязательное.

**Comment by ostiwe** [comment]
Спасибо, это помогло решить мою проблему

**Comment by stalkerg** [comment]
@ostiwe  `/pictures/view_posts/` ручка скоро будет убрана и вместо неё использоваться `/api/v3/posts` страница передаётся через GET - `page`.

**Comment by ostiwe** [comment]
@stalkerg Привет, можешь подсказать пожалуйста по какому роуту конкретно можно получать арты?

Просто, каждый раз когда я запрашиваю https://anime-pictures.net/api/v3/posts?page=1 например - получаю 404 ошибку, подумал, что из-за user-agent, поставил `ostiwe-com/vksaver` - все равно результат тот же

**Comment by stalkerg** [comment]
@ostiwe а вам зачем? Мы сейчас в затруднительном положении и лишних мощностей нет. Вы читали новости?
В целом API вы можете использовать с домена `api.anime-pictures.net` но везде стоит защита cloudflare и автоматизированый трафик может блокировать. 
И да, `cdn.anime-pictures.net` больше не работает.

**Comment by ostiwe** [comment]
> @ostiwe а вам зачем? Мы сейчас в затруднительном положении и лишних мощностей нет. Вы читали новости?
> 
> В целом API вы можете использовать с домена `api.anime-pictures.net` но везде стоит защита cloudflare и автоматизированый трафик может блокировать. 
> 
> И да, `cdn.anime-pictures.net` больше не работает. 

Только сейчас увидел, печально видеть, что вас атакуют ботами (и с hetzner). Постараюсь как-нибудь помочь через kofi, а то через рф сложновато наверное будет. Если есть иной способ помочь финансово - был бы рад про него узнать. 

> а вам зачем?

Если вкратце - у меня есть веб приложение для поиска и публикации артов (anime-pictures, danbooru), используется сейчас только мной для паблика в ВК https://vk.com/caressemoi

Особой жесткой нагрузки я вроде не создаю, но тут вам решать, можно использовать или нет.

**Comment by MiTereKun** [comment]
**ostiwe**, 

> Если вкратце - у меня есть веб приложение для поиска и публикации артов (anime-pictures, danbooru), используется сейчас только мной для паблика в ВК https://vk.com/caressemoi

Отмотал до ноября, там в основном пиксив и твиттер в источниках, пара других сайтов, даже картиночный сервис никовидео, но anime-pictures.net ни разу не встретил. Или приложение как раз вставляет в поле источник оригинальную ссылку автора?
Мне делали [js без использования api для публикаций вк](https://github.com/7nik/ap-vk-poster), но и задачу оно выполнят в виде рекламы ap, а не автора картинки. У меня много реальной работы, с годами без рекламы некогда успешный паблик стал угасать, таргетинговое название уже так сильно не помогает [vk.com/mjvart](https://vk.com/mjvart)

**Comment by ostiwe** [comment]
> Или приложение как раз вставляет в поле источник оригинальную ссылку автора?

Да, ищется в тегах автор и формируется ссылка

**Comment by stalkerg** [comment]
Хотелось бы и ссылку на нас получить.

**Comment by ostiwe** [comment]
Окей, если таким образом смогу беспрепятственно использовать ваш api

**Comment by stalkerg** [comment]
Окей, было бы неплохо. Я выше дал новый домен.
