### ISSUE TITLE
Маленькие checkbox и radio

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#2]
В параметрах поиска картинок и настройках поиска тега checkbox и radio можно было бы позаворачивать в label, а то тыкать в область 13х13 пикс. не шибко удобно.

**Comment by iDolmatov** [comment]
Согласен, что это было бы удобно и не требует больших изменений.
Пример:
`<label><input type="checkbox" name="ext_jpg" value="jpg"> jpeg/jpg </label>`

**Comment by stalkerg** [comment]
OK! Сделаю на днях!

**Comment by stalkerg** [comment]
Вроде сделал - спасибо.

**Comment by iDolmatov** [comment]
Думаю, что >=x <=x >=y <=y можно было бы тоже сделать обёртку.
Также их можно разграничить через &nbsp - по 4 выглядит нормально:
`<label><input type="radio" name="res_x_n" value="1" id="res_x_1_id" false="">&gt;=x</label>&nbsp;&nbsp;&nbsp;&nbsp;`
