### ISSUE TITLE
Избранное для new и pre картинок.

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#21]
Сейчас могут возникать ситуации, когда есть картинка, но ты не можешь добавить её в избранное.
1. PRE
Добавить кнопку "Добавить в предварительные избранные" на странице картинки.
После её нажатия менять на "Удалить из предварительных избранных".
Данные картинки отображать в отдельной категории "предварительные избранные". Категория не удаляется. Управление категорией картинки возможно только в рамках данных кнопок.

После смены PRE на опубликованную перемещать в стандартную категорию. Для этого нужна отдельная база (раздел базы) картинок, которая меняется при установке (снятии) статуса pre.

При управлении избранным со стороны пользователя ID картинки присваивается ID пользователей с разделителем и заносится в отдельную колонку (графу) базы.
В момент удаления картинки из базы PRE картинок для каждого пользователя перевести картинку в стандартные избранные.
По идее не должен быть перевод картинки из PRE в BAN (ведь она почти одобрена), но для таких случаев может потребоваться сначала выполнение запроса удаления картинки из избранного. а затем удаление из базы PRE.
2. New
Иногда, при загрузке картинки сайт сообщает, что картинка уже есть. При этом картинка тебе нравиться, поэтому ты бы хотел её загрузить или добавить в избранное.
Хотелось бы для картинок new после получения сообщения о дубликате видеть справка от уведомления кнопку "i".
Суть кнопки, которая должна быть вкратце описана во всплывающей подсказке или в справке к сайту:
При нажатии кнопки для профиля пользователя формируется запрос для автоматической проверки статуса картинки.
Работа запроса и кнопки:
Нажатие кнопки формирует список картинок по их ID для уведомления и ID пользователей, которым отправить уведомление. Определённый скрипт на сайте раз в N минут (допустим 10), проверяет статус картинки, если он изменился с NEW на другой, то уведомить пользователя об обновлении статуса картинки.
Уведомление отправляется в ЛС с краткой сутью уведомления (картинке ZZZ присвоен статус YYY) и превью картинки. По возможности, для статуса PRE или опубликованной, формировать линк на картинку через превью.
После отправки ЛС всем пользователям удалять строку с ID из базы.

**Comment by iDolmatov** [comment]
Текста много, поэтому можно не сразу понять суть предложений.

**Comment by 7nik** [comment]
Я некоторые моменты по три раза перечитывал.
Пересказ:
1. Возможность добавлять прешки в особое избранное, которое потом, при публикации картинки, переносятся в избранное по-умолчанию.
2. Возможность подписаться на изменение статуса у новой картинки через сообщение о том, что залитая картинка уже есть на базе.

Моё мнение:
а) не проще всё свести только к пункту 2, просто также подписываться на прешки?
б) не проще просто просматривать все опубликованные картинки? или боишься проморгать ту самую?

P.S.: явно есть некоторый бэкдор, который позволяет звёздить и добавлять прешки в избранное ([пример](https://anime-pictures.net/pictures/view_post/528490?lang=ru)).

**Comment by iDolmatov** [comment]
Бывает не смотришь новые картинки долгое время, а за это время новых картинок за сотню. Или просто модератор постарался.
Поэтому просто просматривая много картинок за раз можно пропустить ту единственную.

Здесь вообще зависит от возможностей владельца сайта, чтоб не переписывать весь сайт.
Хотелось бы меньше телодвижений.
Хотел сначала просто написать про добавление не финального статуса картинок в избранное.
Но так нельзя, так как статус BAN или NEW будет просто висеть без возможности управления им.

**Comment by stalkerg** [comment]
добавлять pre в избранное можно, на данный момент это специально запрещено т.к. это стимул того кто залил добить теги и есть шанс что из пре картинка будет забанена. Короче на то оно и пре. 

Второй пункт я так понял это про то что, сообщать пользователю который залил картинку о том, что его картинка поменяла статус?

**Comment by iDolmatov** [comment]
Второй пункт:
Бывает "Я" заливаю картинку, но она уже есть у пользователя "Не Я", но ещё не проверена (статус new). О дубликате сообщает загрузчик.
Хотелось бы возможность добавить уведомление о статусе картинки другого пользователя, чтоб я мог её после одобрения добавить в избранное.

**Comment by iDolmatov** [comment]
Что-то как-то туманно.
