### ISSUE TITLE
Рекомендация связки

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#22]
Просьба добавить аналог рекомендации тегов. но для связки.
Для экономии места разместить одну строку по тегами, пишет ОК после отправки ID или полной ссылки. Отображать рекомендованные связки только в профиле пользователя.

Со стороны модераторов отдельный раздел, где показаны рекомендации.
Вид списка, по аналогии с текущими карточками связок у картинок.
[Картинка у которой дана рекомендация] [картинка для связи 1] V/X [картинка для связи N] V/X
Т.е. галочка и крест под или возле рекомендованной картинки.

Это упростит связку картинок без необходимости пользователям писать в чат или комментарий рекомендации, а модераторам не нужно искать картинку по ID. достаточно открыть раздел рекомендаций.

**Comment by 7nik** [comment]
Да там небось будет один спам, как с половиной реком. тегов.
Мне позаворачивать айдишки в <a> секундное дело.
В общем я к этой идее нейтрально отношусь. 

P.S.: хм, мне казалось что сюда мы добавляем то, что _нужно_ сделать, а в [список предложений](https://docs.google.com/document/d/1E3uUWkiGG8g2mcn3qynBSoPmah8KG0RWB1Kl_5j0aKw/edit), то с чем надо решить нужно ли оно и в каком виде.

**Comment by iDolmatov** [comment]
> Да там небось будет один спам, как с половиной реком. тегов.
Может где-то и будет, но не обязательно будет весь спам сортировать. Но не думаю, что как с тегами.
Теги ставят рекомендованные ошибочно по незнанию или что-то лишнее придумали. А сравнить пару почти одинаковых картинок почти любой сможет.

Будете видеть превью одной картинки и справа превью другой картинки. Картинки одинаковые? Жми галочку. Разные? Оставь на потом или потрать одну секунду нажать крест.

Если нужно, то могу "составить\нарисовать" превью идеи.
__________________________________
Мне написал stalkerg:
> https://github.com/stalkerg/anime-pictures/issues -- теперь тут баги и предложения

**Comment by 7nik** [comment]
Сравнивать по превью плохая идея - они могут быть идентичными и тогда одну их них надо отправлять в баню.
Сама идея понятна. Но загнать бы сюда всех модеров, чтобы послушать их мнение обо всех идеях.

**Comment by stalkerg** [comment]
> P.S.: хм, мне казалось что сюда мы добавляем то, что нужно сделать, а в список предложений, то с чем надо решить нужно ли оно и в каком виде.

Тут есть свои теги так что всё ок.

**Comment by S-kidysh** [comment]
Честно говоря, лично мне как-то вообще параллельно что среди связанных будет кандидат на бан.
У нас сейчас множество других проблем с нехваткой рук и т.п.
По превью стразу понятно связаны или нет, так что это очень удобно.
Если кто-то потом заметит, что картинку стоит забанить, так даже будет легче сравнить со связанными картинками.
Я всеми лапами за, честно.

**Comment by weyde** [comment]
я за. так пойдет быстрее и все смогут при желании в этом участвовать, а не как сейчас, одному модеру накинули тонну и он вместо публикаций сидит и разгребает всё это один
