### ISSUE TITLE
Перевод сайта

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#23]
Может на github создашь файл перевод с колонками или несколько файлов для каждого языка, где каждый пользователь этого сайта сможет дополнить не переведённые строки?

Таким образом можно устранить ошибки в отсутствующих строках перевода.
Правда не знаю как сейчас сайт работает с языками, единый файл для языка (языков) или просто подгружается другая версия страницы со встроенным текстом (по сути, не рациональный метод).

**Comment by iDolmatov** [comment]
P.s. https://anime-pictures.net/pictures/anime_girls/0?lang=en содержит только русское описание.

**Comment by 7nik** [comment]
Я думал попозже поднять тему переводов, но вообще идея обнародования текущих переводов, чтобы другие могли доперевести это отличная идея.

**Comment by iDolmatov** [comment]
Общие переводы стандартная практика для общедоступных проектов, когда над переводом работает не один автор через личку разработчика.

**Comment by stalkerg** [comment]
У нас есть платный аккаунт тут https://poeditor.com/ могу добавить. Главная проблемма это:
1. дорого, на том тарифном плане что мы сидим не хватает разрешённых  строк перевода.
2. всё же бывает влом от туда качать перевод на сайт или синхронризировать правки которые я внёс напрямую на сайт. 
3. думал отказаться от этого сервиса но пропустил оплату...  так что ещё пол года он у нас.

**Comment by 7nik** [comment]
Это, я думая, уже можно закрыть.

**Comment by stalkerg** [comment]
https://github.com/stalkerg/anime-pictures/tree/master/i18n -- собственно все тут.

**Comment by iDolmatov** [comment]
> собственно все тут.

Если так можно считать. 
Проверил несколько файлов и не нашёл "Corrected tags for latest 20 pictures", как и ранее.
https://raw.githubusercontent.com/stalkerg/anime-pictures/master/i18n/mjvartorg.pot
https://raw.githubusercontent.com/stalkerg/anime-pictures/master/i18n/ru/LC_MESSAGES/mjvartorg.po
https://raw.githubusercontent.com/stalkerg/anime-pictures/master/i18n/en/LC_MESSAGES/mjvartorg.po
Либо нужно синхронизировать (обновить) файлы, либо строка где-то отдельно в коде без вынесенного перевода.
Ещё недавно заметил ожидание перевода: https://anime-pictures.net/index/faq?lang=es

**Comment by 7nik** [comment]
Ну перевод ФАКа там вообще хитрым образом.
К стати, у китайского ФАКа сейчас вообще нет никакого перевод и он откатывается к английскому.

**Comment by MiTereKun** [comment]
да это всё по тому, что саму эту статью надо переделывать о чём шли разговоры ещё с моей регистрацией.
По переводу меня больше беспокоит `mjvartorg/templates/profile/ext_profile.mako:177`
`Наиболее популярные картинки` заменить на `Наиболее популярная картинка`, о чём я ещё говорил в последнем пункте [тут](https://github.com/stalkerg/anime-pictures/issues/98), а именно из-за того, что там никогда не бывает несколько картинок. Во всех переводах картинка так же стоит в единственном числе

**Comment by 7nik** [comment]
1. Делаешь форк
2. корректируешь перевод
3. предлагаешь пул-реквест
...
PROFIT!

**Comment by stalkerg** [comment]
@iDolmatov отлично! Я обновлю! Заведи отдельный таск.

**Comment by stalkerg** [comment]
@MiTereKun если не можешь сделать PR заведи хотя бы отдельный таск и я его решу. Это крайне простая фича. (надо тут тег для таких задач добавить)

**Comment by iDolmatov** [comment]
> По переводу меня больше беспокоит `mjvartorg/templates/profile/ext_profile.mako:177`
Можешь сверить https://github.com/stalkerg/anime-pictures/pull/107/files
#104
