### ISSUE TITLE
Выделения тега только для тегов-персонажей

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#25]
Выделение тегов изначально предназначено только для персонажей, так что имеет смысл оставить эту кнопку только для тегов-персонажей. Исключением могут быть, разве что, косплейные теги, когда на картинке [много косплееров](https://anime-pictures.net/pictures/view_post/524527?lang=ru). 
Также изредка, но кто-нибудь зачем-то выделяет теги на картинке, особенно убивает когда выделяют тег высокое разрешение.

**Comment by stalkerg** [comment]
Не уверен.... мне кажется что то тут ограничевать это себе дороже.

**Comment by 7nik** [comment]
Можно только простым пользователям ограничить.

**Comment by iDolmatov** [comment]
Можно объектные теги разрешить (небо, девушка, и т.п.), а описательные запретить (красное платье, синее небо, узор в горошек).

**Comment by blackbloodoff** [comment]
Предпочла бы только персов, не вижу смысла проставлять еще косплей.

**Comment by weyde** [comment]
поддерживаю. случаев когда реально надо выделить объект на картинке и когда это к тому же кто-то делает, по пальцам можно пересчитать.
а косплейные теги не стоит выделять, ибо они будут перекликаться с тегом персонажей, очень очень плохо это. при наведение на персонажа будет показываться только одно из выделений и пользователь узнает лишь половину инфы.

**Comment by 7nik** [comment]
> косплейные теги не стоит выделять

Я для тега перса выделяю только голову, а для коспейнного - тело.
