### ISSUE TITLE
Растягивание превью на десктоп версии 

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#26]
При ширине вкладки 1000 пикс. и менее картинки подгоняются под ширину экрана. Учитывая что качество превью даже при 100%-м масштабе не такое уж и супер, то при растягивании оно ещё хуже. 
Сжатия это не касается.

**Comment by stalkerg** [comment]
Это скорее бага после моих правок для подержки мобильной версии.

**Comment by stalkerg** [comment]
Так, а почему у тебя вкладка меньше 1000 пикселей? Всё что меньше 1000 пикселей у нас это мобильные устройства.

**Comment by stalkerg** [comment]
Пофиксил, проверяй.
