### ISSUE TITLE
Раздел "протегируй меню"

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#34]
Вернуть старый раздел в новом виде.
Добавить отдельный поиск в разделе:
Pre, с тегом tagme (artist), tagme (character), протегируй меня
Можно перевести фильтры поиска:
Предварительные, без артиста (автора), без персонажа. мало тегов.

Вверху краткие правила раздела:
1. Обычные теги можно ставить только для предварительных, для остальных рекомендовать;
2. Ссылку на артиста (автора) и/или описание персонажа писать в комментарии, там где пишите несуществующие теги.

P.S. Предложения переношу из лички, которые можно объяснить.

**Comment by weyde** [comment]
вообще не поняла зачем это, тем более что половину из предложенного и так можно сейчас сделать
+ мы специально убрали этот раздел, туда никто не заходит, модераторы о нем тоже постоянно забывали и картинки там могли по пол года висеть, а то и дольше

**Comment by iDolmatov** [comment]
Отказано модератором, одобрения другими участниками нет.
