### ISSUE TITLE
Автозамена разделителя

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#35]
При расширенном поиске заменять в конце || на && и наоборот, если строка заканчивается одной из этих комбинаций.

> Защита от нескольких конъюнкций (&&) и/или дизъюнкций (||) идущих подряд в поисковом запросе.

**Comment by 7nik** [comment]
Они же в расширенном поиске ставятся только когда нажмёшь на них или наберёшь. 
Да и как избежать бесконечной замены || на && и обратно? Точнее как код должен узнать когда нужно делать замену, а когда нет?

**Comment by iDolmatov** [comment]
Запоминать нажата кнопка или введён символ в строку (вставлен набор символов).
Но технически тонкости неизвестны, насколько можно отслеживать выполняемое действие.

Сложностей не должно возникнуть:
Сейчас ведь выполняется поиск вводимых или вставленных символов для поиска тега.
Достаточно при запросе тега или при нажатии другой кнопки (|| или &&) сбрасывать 1 в буфере обмена для статуса кнопки.

**Comment by stalkerg** [comment]
>При расширенном поиске заменять в конце || на && и наоборот, если строка заканчивается одной из этих комбинаций.

Зачем!?

**Comment by 7nik** [comment]
Нормальные люди и не пишут, хотя есть тестеры, те и не такое понапишут :)
А теперь нормально сформулируем предложение:
Защита от нескольких конъюнкций (&&) и/или дизъюнкций (||) идущих подряд в поисковом запросе.

**Comment by stalkerg** [comment]
> Защита от нескольких конъюнкций (&&) и/или дизъюнкций (||) идущих подряд в поисковом запросе.

Во! Другое дело! Это да, не трудно в целом наверное. Хотя явно с низким приоритетом.

**Comment by iDolmatov** [comment]
#101
