### ISSUE TITLE
Исключать похожие картинки при наличии их в связанных

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#37]
Предлагаю сделать автоисключение картинки из похожих, если есть она в связанных. https://anime-pictures.net/pictures/view_post/317805?lang=ru

**Comment by iDolmatov** [comment]
Вроде неактуально. Сейчас рекомендуемые генерируются случайно и тестовая проверка не показала наличие проблемы.

**Comment by MiTereKun** [comment]
А с другой стороны теперь по рекомендованным нельзя наткнуться на оставшиеся несвязанные арты
