### ISSUE TITLE
Заменить редирект на все картинки

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#38]
Предлагаю или добавить промежуточную страницу, или редирект на главную страницу.
Или придумать отдельную страницу 404, когда будут показаны последние X (5-15) картинок со всеми плюшками расширенного поиска. В внизу кнопка "Посмотреть все".

Мне удобно сразу видеть много. Но при ADSL или мобильном интернете лишняя загрузка чревата трафиком.

**Comment by 7nik** [comment]
>  ADSL или мобильном интернете 

> заходить на сайт посвящённый картинкам и надеяться на низкий трафик

ну и хохма

> промежуточную страницу, или редирект

между кем и чем?

**Comment by stalkerg** [comment]
> Предлагаю или добавить промежуточную страницу, или редирект на главную страницу.

откуда и куда? ничерта не понял.

**Comment by iDolmatov** [comment]
Это когда ошибочно указал другой ID картинки, например https://anime-pictures.net/pictures/view_post/489666?lang=ru

**Comment by S-kidysh** [comment]
это действительно странно показывать вообще все картинки, если нет одной по конкретному айди.. или когда юзер пытается зайти на new или ban картинку.

**Comment by 7nik** [comment]
> юзер пытается зайти на new или ban картинку.

Обычные пользователи вообще не должны даже пытаться заходить на чужие новые и забаненные картинки. А ещё ведь есть удалённые картинки.

Но вообще было бы не плохо сделать страницу для ошибок 404 и 403 и тогда их можно будет отображать в этих ситуациях.

**Comment by stalkerg** [comment]
Это было сделанно специально, что бы увеличить вовлезённость пользователей. 
Дело в том что куча народу переходит по старым ссылкам с других сайтов и юзер скорее удёт с сайта если будет 404. Хотя возможно как то это стилизовать....

**Comment by 7nik** [comment]
Можно сделать редирект с таймером:
Запрашиваемая страница не существует / У вас не достаточно прав для просмотра этой страницы.
Вы будете перенаправлены на главную страницу через 5... 4... 3... 2... 1... 0.

**Comment by S-kidysh** [comment]
> Запрашиваемая страница не существует / У вас не достаточно прав для просмотра этой страницы.
Вы будете перенаправлены на главную страницу через 5... 4... 3... 2... 1... 0.

90% несовершеннолетних юзеров испугаются и съе**тся после этой фразы, так что не самый лучший варик.

> Хотя возможно как то это стилизовать....

уже было предложено как:

> Или придумать отдельную страницу 404, когда будут показаны последние X (5-15) картинок со всеми плюшками расширенного поиска. В внизу кнопка "Посмотреть все".

имхо неплохой вариант, при этом доходчиво написать в шапке, что **такой страницы нет**, и предложить посмотреть другие картинки сайта.

**Comment by iDolmatov** [comment]
Сомнительно.
