### ISSUE TITLE
Ссылки на view_posts_v2

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#41]
При поиске картинок, ссылки всех номеров страниц введут на [view_posts_v2](https://anime-pictures.net/pictures/view_posts_v2/1?lang=ru) вместо [view_posts](https://anime-pictures.net/pictures/view_posts/1?lang=ru). И тех, кто решит открыть другую страницу поиска в новой вкладке ждёт сюрприз.

**Comment by stalkerg** [comment]
Да! Так и было задуманно пока не получается ВСЮ страницу переписать на Tornado

**Comment by 7nik** [comment]
К о том, что может не ссылаться на v2? 
Когда я первый раз туда попал, то подумал, что что-то сломалось и css не подгрузились.

**Comment by stalkerg** [comment]
Так, это надо поправить, так как теперь всё на торнадо и надобности в v2 просто нету.

**Comment by stalkerg** [comment]
Исправил.
