### ISSUE TITLE
Пробелы вокруг разделителей 

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#42]
Пробелы вокруг разделителей портят запрос: если это ||, то тег с пробелом ищется так же как несуществующие теги, а если &&, то вообще ничего не находит.
можно на `oninput` повесить след. обработчик:
```javascript
function (e) {
    const oldVal = e.srcElement.value;
    const newVal = oldVal.replace(/\s*(&&|\|\|)\s*/g, "$1");
    if (newVal !== oldVal) {
        e.srcElement.value = newVal;        
    }
}
```
Также можно сразу добавить "автозамену разделителя", но тогда нужно вызывать ф-ю ещё и при вставке разделителя:
```javascript
function (e) {
    const oldVal = e.srcElement.value;
    const newVal = oldVal.replace(/\s*(?:\s|&&|\|\|)*(&&|\|\|)\s*/g, "$1");
    if (newVal !== oldVal) {
        e.srcElement.value = newVal;        
    }
}
```
А потом я подумал, решил почему бы не добавить автозамену " AND ", " И " на &&, а " OR  ", " ИЛИ " на ||:
```javascript
function (e) {
    function replacer(str, p1) {
        switch (p1) {
            case " AND ":
            case " И ":
                return "&&";
            case " OR ":
            case " ИЛИ ":
                return "||";
            default: return p1;
        }
    }
    const oldVal = e.srcElement.value;
    const newVal = oldVal.replace(/\s*(?:\s|&&|\|\|| AND | OR | И | ИЛИ )*(&&|\|\|| AND | OR | И | ИЛИ )\s*/g, replacer);
    if (newVal !== oldVal) {
        e.srcElement.value = newVal;        
    }
}
```

**Comment by 7nik** [comment]
И так в std.js надо добавить:
на 301-ой строке: 
```javascript
// replace a sequence of delimiters and spaces with the last in the sequence delimiter
// also replace " AND ", " И " with "&&" and " OR ", " ИЛИ " with "||"
this.AutoComplete.prototype.clean_query = function() {
    function replacer(str, p1) {
        switch (p1) {
            case " AND ":
            case " И ":
                return "&&";
            case " OR ":
            case " ИЛИ ":
                return "||";
            default: return p1;
        }
    }
    const old_val = this.input_tag.value;
    const new_val = old_val.replace(/\s*(?:\s|&&|\|\|| AND | OR | И | ИЛИ )*(&&|\|\|| AND | OR | И | ИЛИ )\s*/g, replacer);
    if (new_val !== old_val) {
        this.input_tag.value = new_val;        
    }
}
```
на 298-ой строке: 
```javascript
this.input_tag.addEventListener("input", function(event){
    self.clean_query();
}, true);
```
на 279-ой строке: 
```javascript
// fix changes made by buttons && and ||
self.clean_query();
```

P.S.: Комменты? Зачем? Я же и через пять лет буду прекрасно помнить что, где и зачем я написал!

**Comment by 7nik** [comment]
forever_alone.jpg

**Comment by stalkerg** [comment]
1. Я не уверен что это вообще проблемма.
2. Её надо решать на сервере.

**Comment by stalkerg** [comment]
Поправил, теперь пробелы убираются при поиске тега. НО! В любои случае запросс типа linux&& будет выдавать пустоту так как это бай дизайн да и логично в целом.

**Comment by 7nik** [comment]
1. когда копипастишь теги ручками, то иногда захватывается пробел и при дописывании запроса случается казус
2. полностью согласен.

Тут скрипт также делает [автозамену разделителя](https://github.com/stalkerg/anime-pictures/issues/35), но её правильнее делать тоже на сервере, да и это уже совсем другая история.

Здесь осталось только пофиксить ту же проблему для запрещённых тегов и в целом можно закрывать.

**Comment by stalkerg** [comment]
Сделал. Если что будет ещё не работать в этой теме то открывай заново эту задачу.
