### ISSUE TITLE
Переключение языка сайта

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#43]
Язык сайта указывается в ссылке, поэтому иногда, при переходе по [некоторым ссылкам](https://anime-pictures.net/pictures/view_post/528261?lang=fr) язык сайта неожиданно переключается, а убрать от туда его нельзя во имя гугла. 
Предлагаю для зарегистрированных пользователей игнорировать язык в ссылке, а лучше редиректить на язык указанный в куках пользователя или вообще БД. А для того, чтобы они могли переключать язык, в форму выбора языка добавить `<input type="hidden" name="force" value="1">` как идентификатор того, что это осознанный выбор пользователя.

**Comment by stalkerg** [comment]
В этом резон есть... пока приоритет у нас урлу, потом кукам, потом настройкам браузера.

**Comment by stalkerg** [comment]
Так, думаю даже без force будет работать. Т.е. просто для зареганных пользователей меняем порядок выбора языка. Звучит логично.

**Comment by 7nik** [comment]
Что-то я проглядел, что запрос уходит на отдельную страницу. Тогда да, можно обойтись и без force. А вообще можно просто поменять приоритет источников выбора языка: куки/БД, урл, настройки браузера.

**Comment by stalkerg** [comment]
Сделал, проверь пожалуйста чательно... там логика получается зубодробительная.

**Comment by stalkerg** [comment]
Вроде ошибок не выявили, закрываю.
