### ISSUE TITLE
Алиасы переносятся

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#44]
При переносе тегов, алиасы тоже копируются и, как результат, кол-во их использованний становится больше единицы, что, наверное, не очень хорошо.

**Comment by weyde** [comment]
вот именно поэтому всегда говорю старайтесь ставить на самую последнюю в списке тега картинку и лучше которая в бане. такие редко воскрешают.
но мысля понятна и правильна. поддерживаю

**Comment by stalkerg** [comment]
Поправил, теперь не копирует.
