### ISSUE TITLE
Баг с подписками

### ISSUE THREAD

**Issue by S-kidysh** [stalkerg/anime-pictures#48]
В поиске по всем картинкам: вбиваешь единственный нужный тег - подписка не отображается, лечится обновлением страницы.
![1](https://user-images.githubusercontent.com/29707031/28418698-546832fa-6d65-11e7-93f2-402c8fae3859.png)

**Comment by stalkerg** [comment]
Пока это не столько бага сколько фича. Ограничение совместного использования двух фреймворков.

**Comment by S-kidysh** [comment]
хм окей.
сюда же напишу: слева без подписки, справа с ней.
![2](https://user-images.githubusercontent.com/29707031/28419906-29e40adc-6d69-11e7-98bf-b4a5491ea3c2.png)
отсюда небольшое смещение фразы

**Comment by 7nik** [comment]
браузеры же любое кол-во подряд идущих пробелов и ентеров отображают как один пробел

**Comment by S-kidysh** [comment]
мб для красоты кода)
в любом случае в первом варианте нет ни пробела, ни энтера

**Comment by stalkerg** [comment]
Это никак не должно влиять. Пробел есть там и там, а потом там вообще BR. 
Можешь показать в браузере как это смещение работает?

**Comment by 7nik** [comment]
![image](https://user-images.githubusercontent.com/29704098/28442626-ef61e112-6db9-11e7-894e-6c959355afc1.png)
Ты об этом смещении? Я его еле заметил даже специально ища.

**Comment by stalkerg** [comment]
Убрал все пробелы.

**Comment by S-kidysh** [comment]
> Убрал все пробелы.

сэнкс)

> Я его еле заметил

Ну всмысле? это сразу заметно, если пощёлкать по вкладкам туда-сюда пару раз. Таким же способом можно легко увидеть мелкие различия на пикчах.
Поэтому сразу в код полез, чтобы узреть разницу.

**Comment by 7nik** [comment]
Кажется это уже исправленно.

**Comment by stalkerg** [comment]
Было исправлено с переходом на новый движок.
