### ISSUE TITLE
Расширение свойств тегов

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#49]
Первое – [несколько родителей](https://github.com/stalkerg/anime-pictures/issues/58), второе – [динамическое кол-во имён тега](https://github.com/stalkerg/anime-pictures/issues/59).
Третье - отказаться от тегов только в нижнем регистре. Для меня - писать чьё-то имя/название с маленькой букве = неуважение, и не важно что это вымышленные персонажи, имя есть имя.

Сейчас, если в названии тега есть хоть одна буква в верхнем регистра (все совершают промахи), то тег не найдётся по этому имени.

**Comment by 7nik** [comment]
Третье - отказаться от тегов только в нижнем регистре. Для меня - писать чьё-то имя/название с маленькой букве = неуважение, и не важно что это вымышленные персонажи, имя есть имя.

**Comment by stalkerg** [comment]
Думаю это всё должны быть отдельные ветки обсуждения.

На счёт родителей - если больше одного родителя то у нас получается граф, и он куда сложнее того что есть сейчас. У нас уже работает система определения циклов и усложнять всё это мне пока боезно... во всяком случае без плана. 

Несколько полей "тега" это то о чём я думал давно но пока не придумал как это сделать правильно.
Маленькие буквы, это повод не искать без учёта регистра, что медленно или полагаться на lower при построении индекса. Сразу много мест появляется где можно отстрелить себе ногу или сделать поведение для пользователя не очевидным.

**Comment by 7nik** [comment]
И в итоге я на днях споткнулся на теге `渣音Re.`, который был в базе, но не находился потому, что там R в верхнем регистре.

**Comment by stalkerg** [comment]
Так надо поставить таск, что бы при добавлении новых тегов, всегда в нижний регистр переводилось, принудительно. 
Ну и было бы отлично если сделать отдельный таск по множеству имён тега.

**Comment by weyde** [comment]
1. ну для некоторых тегов действительно можно было бы сделать несколько родителей (но не для оригинальных персов), но я лично боюсь что даже если мы сделаем такую фичу будет множество ошибок с её использованием. у каждого модератора свое предствление о тегах и не всегда верное, мы таким образом только сами себе геморой создадим.
2.ну это правильная мысля, сама всё время голову ломаю как сделать алисы к некоторым тегам
3. тут я очень и очень против, по многим причинам, но первая и основная - уродство. это же отвратень будет + это нормально в интернетах всё писать с маленькой буквы
