### ISSUE TITLE
Баг с отображением

### ISSUE THREAD

**Issue by S-kidysh** [stalkerg/anime-pictures#51]
**1)** Во вкладке "новые изображения" если искать какой-нибудь тег, то покажутся картинки с тегом только из тех, что были в этой вкладке (правильно), но напишет "в запросе N картинок", где N - кол-во всех картинок с тегом из базы  (неправильно). Отсюда разница в отображении.
![1](https://user-images.githubusercontent.com/29707031/28514914-6ac91968-7064-11e7-802b-0634e5fe8509.png)
**2)** Далее, если листать странички, которых не должно быть, вижу вот это:
![2](https://user-images.githubusercontent.com/29707031/28515032-d49f9736-7064-11e7-8cbc-c156228e907b.png)
**3)** Если вернуться на нулевую страницу - вижу вот это:
![3](https://user-images.githubusercontent.com/29707031/28515190-5ebc5c38-7065-11e7-9ae1-8af06aea4c71.png)

**P.s.** Насчёт первого пункта: будет всё нормально, если добавить: больше одного условия/указать разрешение/указать расширение.

**4)** Если просто во всех картинках искать один тег и указать: соотношение сторон или цвет, то вылезают всё те же баги.

**Comment by 7nik** [comment]
1 - неправильно считает даже если выставить поиск картинок за последний день/неделю/месяц или включить откл. картинки модераторов или блокировку эротики.
2, 3 - это ты зашёл на /pictures/view_posts_v2/ она, вроде как, ещё не готова.

**Comment by S-kidysh** [comment]
упс

**Comment by S-kidysh** [comment]
окей, тогда проблема только в подсчёте

**Comment by MiTereKun** [comment]
Похоже view_posts_v2 теперь работает на ровне с "простым" view_posts. 
Проблему с подсчётом можно обойти ручной прописью номера в низу страницы, или в адресной строке. Фортуной страница может отобразиться в середине графического списка со страницами... Или нет. Остановиться каких-нибудь 3 квадратика и левое трёхзначное число (при выставленной сотке картинок на страницу). Проблема возникает почти всегда в разделе your own stars. Полностью решается если изменить количество элементов на страницу в настройках

**Comment by stalkerg** [comment]
Так, на днях поправим.

**Comment by stalkerg** [comment]
Проверяйте, кажется поправил.

**Comment by 7nik** [comment]
Берём [девушку](https://anime-pictures.net/pictures/view_posts/0?search_tag=девушка) и:
- отмечаем откл. картинки модераторов;
- задаём соотношение сторон;
- устанавливаем цвет.
В каждом из случаев кол-во картинок считается не правильно, хотя иногда при совместном использовании считает нормально о_О.

**Comment by iDolmatov** [comment]
Так и не понимаю, что обсуждают.
Для меня https://anime-pictures.net/pictures/view_posts_v2/1?lang=ru и https://anime-pictures.net/pictures/view_posts/1?lang=ru одинаковые, только при смене страниц по первой ссылке пересылает на второй вариант.

**Comment by 7nik** [comment]
Теперь выглядят одинаково.
Тут остался только баг с неправильным подсчётом кол-ва картинок в некоторых запросах.

**Comment by stalkerg** [comment]
>отмечаем откл. картинки модераторов;
>задаём соотношение сторон;
>устанавливаем цвет.

ok, поправлю, теперь всё гораздо яснее.

**Comment by MiTereKun** [comment]
> Проблему с подсчётом можно обойти ручной прописью...

Только в звезданутых картинках, в избранных не помогает. И ещё заметил, что количество картинок и страниц в этих разделах совпадают и оба числа не правильные, при том!! Если в настройках прописать количество элементов на страницу каких-нибудь 38, а не 100 как у меня всегда стоит - числа в разделах все равно останутся одинаковыми, но в избранном появится огромное количество страниц, на которых нет картинок (но они есть в your own stars)

**Comment by iDolmatov** [comment]
MiTereKun, написал об этом ранее https://github.com/stalkerg/anime-pictures/issues/52#issuecomment-340634745

**Comment by stalkerg** [comment]
@7nik проверь пожалуйста ещё раз.

**Comment by 7nik** [comment]
Если искать ровно [один тег + соотношение сторон](https://anime-pictures.net/pictures/view_posts/0?search_tag=%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B0&aspect=16%3A9&order_by=date&ldate=0), то всё ещё неправильно считает, хотя для анонимуса считает правильно.
Также при включенной блокировкой эротики и поиске по одному тегу или пустому запросу неправильно считает.

**Comment by stalkerg** [comment]
Теперь всё должно быть хорошо, проверьте.

**Comment by 7nik** [comment]
У меня всё ок, везде всё правильно считает.

**Comment by stalkerg** [comment]
Ок, закрываю. :)

**Comment by 7nik** [comment]
Прохлопали ещё один кейс: [один тег + запрещённые](https://anime-pictures.net/pictures/view_posts/0?search_tag=%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B0&denied_tags=%D0%BC%D1%83%D0%B6%D1%87%D0%B8%D0%BD%D0%B0&order_by=date&ldate=0&lang=ru), хотя у анонимусов тут опять всё норм.

**Comment by stalkerg** [comment]
Пофиксил, можешь гялнуть. Просто запрещённые теги это как бы не отдельное поле в запроссе... я компилирую один единый  int_query к индексу.

**Comment by 7nik** [comment]
Теперь норм. 
Раз десять перечитывал, но так ничего и не понял.
