### ISSUE TITLE
Поиск по звёзднутым картинкам

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#52]
При нажатии кнопки "Искать" GET-параметр stars_by удаляется и производится обычный поиск. Если его ручками вернуть обратно в url, то все прекрасно работает до следующего нажатия кнопки.

Ну и пора бы его уже сделать список звёзднутых картинок либо полностью публичным, либо полностью приватным.

**Comment by stalkerg** [comment]
Поправил и добавил ссылку в профили. 
Но нам надо будет подумать, как сделать такие страницы более понятными т.к. кроме как по url нельзя понять что ты сейчас ищешь.

**Comment by 7nik** [comment]
Можно просто в области описания искомого тега сообщать:
Картинки загруженные пользователем %юзернейм%
Картинки отмеченные пользователем %юзернейм%
Картинки добавленные пользователем %юзернейм% в избранное (%папка%)

**Comment by iDolmatov** [comment]
Вот не пойму, то ли счётчки тупят, либо я туплю.
https://anime-pictures.net/pictures/view_posts/0?stars_by=25586&lang=ru и https://anime-pictures.net/pictures/view_posts/0?favorite_by=25586&lang=ru показывало по 1036
Поставил звезду без избранного в https://anime-pictures.net/pictures/view_post/537818?lang=ru

Причём видно, что картинко-то разно

**Comment by stalkerg** [comment]
А если добавить ещё? Ок, надо перепроверить.

**Comment by iDolmatov** [comment]
Число обновилось до 1037. 
favorite 387 картинок. stars 1037. Если верно работает показ.
Ставлю в настройках профиля "Количество элементов на страницу" до 80 - всего 387. От 80 - 1037.

**Comment by iDolmatov** [comment]
Если что, то не только у меня.
https://anime-pictures.net/profile/view_ext_profile/71778?lang=ru - вижу всё по 1165.
Забавно видеть 5 избранных 1165 "мифических" избранных.

**Comment by stalkerg** [comment]
Так, поправил, переработал один концепт теперь должно быть всё правильно. (я надеюсь)
Пожалуйста, проверьте.

**Comment by iDolmatov** [comment]
Ошибок не заметил, спасибо.

**Comment by MiTereKun** [comment]
в избранных и звезданутых последние страницы открываются и их разное количество. Значит вроде всё правильно

**Comment by stalkerg** [comment]
Хорошо, тогда закрываю ошибку.
