### ISSUE TITLE
Можно звёзднуть и добавить в избранное картинку с любым статусом

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#53]
Со стороны сервера нет проверки статуса картинки при установке звезды и добавлении в избранное, поэтому можно, независимо от статуса картинки, успешно выполнять запросы (даже типа GET) вручную или вообще добавить на страницу элементы управления этими функциями. 
Этим лайфхаком успешно пользуются некоторые господа, а других господ, подозреваю, жаба давит при виде подобного :)

**Comment by stalkerg** [comment]
Будет исправленно в ближайшнее время.

**Comment by stalkerg** [comment]
Исправил.
