### ISSUE TITLE
IQDB

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#55]
Не знаю с чьей стороны проблемы, но https://iqdb.org/?status=1

> Anime-Pictures | 44 days ago | 44 days ago | 532600 | Update failed 1410 times. (Last reason: Disabled because of broken API )

**Comment by stalkerg** [comment]
ouch... надо автору написать. На самом деле ему нужно очень спецефичный API типо эмуляция данбуру причём их XML варианта.

**Comment by stalkerg** [comment]
Кажется понял в чём дело. Через часов 8 пофикшу.

**Comment by iDolmatov** [comment]
Fixed

**Comment by stalkerg** [comment]
Ещё одна прблемма с ним есть....

**Comment by stalkerg** [comment]
Конкретно с этой проблеммой мы справились, переходим сюда: https://github.com/stalkerg/anime-pictures/issues/56 . (туда и создатель iqdb приглашён)
