### ISSUE TITLE
Ошибка 500 для алиса, если родительский тег удалён

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#57]
https://anime-pictures.net/pictures/view_all_tags/0?search_text=clavicle&tag_desc=&lang=ru -> https://anime-pictures.net/pictures/view_posts/0?search_tag=clavicle&lang=ru
https://anime-pictures.net/pictures/view_all_tags/803?lang=ru - тег "Ключица" 12808 удалён.

Желательно, автоматически удалять алисы при удалении родительского тега.

**Comment by stalkerg** [comment]
Поправил, теперь даже если такое повторится, то ошибки не будет. 
А проблемма вылезла из-за нового скрипта который удаляет массово теги с картинок.
