### ISSUE TITLE
Область выделения тега

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#6]
1. Область выделение тега (персонажа) на картинке может выходить за пределы картинки ([скриншот](https://image.prntscr.com/image/90b7e6f125314b7fb37328175f1c3ba6.png), достаточно не спеша вести курсор) и такая область сохраняется и воспроизводится без проблем. 
2. При ширине окна 1000 пикс. и менее картинка подгоняется под ширину окна, а область выделения тега - нет.
3. Иногда затемнение и область выделения съезжают вправо на 1 пикс.. Пример: [518325 ](https://anime-pictures.net/pictures/view_post/518325?lang=ru)([скриншот](http://image.prntscr.com/image/cae06baeac404afdbb7e5bfd5e244c7a.png)) (Хром 57).
4. При выделении у области есть некий минимальный размер, но если кликнуть где-то в середине и нажать сохранить, то сохранённая область будет меньше чем отображавшаяся при сохранении.

**Comment by stalkerg** [comment]
Похоже, что тут как минимум 3 разных бага.

**Comment by 7nik** [comment]
Ну я их объединил как относящиеся, на мой взгляд, к одному модулю. Но могу его разбить на части.

**Comment by stalkerg** [comment]
На счёт первого - конечно лучше было бы что бы нельзя было увести за границу картинки но это всё не смертельно так как противоречит тому что хочет юзер.

**Comment by 7nik** [comment]
На длинных картинках стартовая область выделения может вылазить за пределы картинки ☺
![image](https://user-images.githubusercontent.com/29704098/31058464-ab7b1514-a6fc-11e7-9442-68338e5a5cdb.png)
