### ISSUE TITLE
Последние избранные - разный вид для пользователя и всех остальных

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#60]
Для пользователя показываются с учётом звёзд, для всех остальных только избранные.
Сначала не понял из-за чего у меня "все" избранные не показывают, поэтом уже понял, что плюсуются звёзды.
Может стоит переименовать раздел с отображением всех картинок из этих категорий для всех.
## Последние избранные ( default, все ) и звёзды (все)
![1](https://user-images.githubusercontent.com/19782385/33909348-32a96af2-dfad-11e7-82f1-62755e7ea1d9.png)
![2](https://user-images.githubusercontent.com/19782385/33909349-32d2b4a2-dfad-11e7-884f-92f4054156fd.png)
![3](https://user-images.githubusercontent.com/19782385/33909350-32fbdd8c-dfad-11e7-9617-97a41d7c2326.png)

**Comment by 7nik** [comment]
Для анонумусов в последних избранных отображаются только картинки без какой-либо эротики (почему? – это вопрос к сталку), при этом все последние избранные картинки действительно избранные тобой.

> плюсуются звёзды.

Пятая звёзднутая картинка (девушка с орлом) ни в каком варианте последних избранных не отображается. И эта картинка, из последних восьми звёзднутых, единственная не в избранном. Также надо помнить, что при добавлении в избранное автоматически ставится звезда.

**Comment by iDolmatov** [comment]
> Для анонумусов в последних избранных отображаются только картинки без какой-либо эротики (почему? – это вопрос к сталку), при этом все последние избранные картинки действительно избранные тобой.
Это известно. Анонимам эротика недоступна.

> Пятая звёзднутая картинка (девушка с орлом) ни в каком варианте последних избранных не отображается.
Пока не всю логику отображения понял.

**Comment by 7nik** [comment]
> логику отображения

В последних избранных картинки отсортированы по дате добавления в избранное, а при поиске как всех избранных так и из конкретной папки они отсортированы по дате публикации.

**Comment by MiTereKun** [comment]
> Для анонумусов в последних избранных отображаются только картинки без какой-либо эротики (почему? – это вопрос к сталку)

- я предлагал вынести тумблер, отвечающий за фильтрацию эротики, в мобильное приложение, но Сталк сказал, что эта галочка - подтверждение пользователя, что он хочет видеть эротику и "чем меньше людей со стороны знают про эту галочку тем лучше" (по вполне понятной причине). В пикисве есть подобная настройка, а санкаку, где всё доступно любому - уже не доступен любому.

у меня провайдер в октябре революцию праздновал, весь месяц - все сайты работали, но кто это повторять булет, лицензию отобрать могут.
А мы с подтверждением показываем и это правильно

**Comment by stalkerg** [comment]
1. В избранных только избранные, не звёзды.
2. Для анонимусов нету порева, все пояснения выше и мне кажется кристально понятны. 
3. Когда открывается конкретная папка с избранными (мы уходим с профиля) то там сортировка уже по тому как ты укажешь. 

увы но это wontfix.
