### ISSUE TITLE
Верхний регистр в названиях тегов

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#63]
Раз уж мы [отказались](https://github.com/stalkerg/anime-pictures/issues/49#issuecomment-340632666) от идеи регистронезависимых тегов, то все новые теги должны автоматически переводится в нижний регистр. Также теги уже содержащие верхний регистр нужно перевести в нижний.

Например большая часть [последних фантазий](https://anime-pictures.net/pictures/view_posts/0?search_tag=%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D1%8F%D1%8F+%D1%84%D0%B0%D0%BD%D1%82%D0%B0%D0%B7%D0%B8%D1%8F) имеют нумерацию в верхним регистре — IV/V/VI/VII/IX/X/XIII/XIV/XV, в результате в автоподсказке для запроса `final fantasy` видим кучу тегов 
![image](https://user-images.githubusercontent.com/29704098/36146706-2f9037e6-10be-11e8-95ba-60a16bb21746.png)
а для запроса `final fantasy x` только три тега и ни одной последней фантазии X/XI/XII/XIII/XIV/XV
![image](https://user-images.githubusercontent.com/29704098/36146744-4aff4ce2-10be-11e8-8799-e09ffff61e91.png)
хотя если нажать кнопку Искать/Добавить, то тег [final fantasy X](https://anime-pictures.net/pictures/view_posts/0?search_tag=final%20fantasy%20x) находится/добавляется на картинку, что весьма контринтуитивно. 

P.S.: почти все теги Шрёдингера это японские названия тегов.
P.P.S.: моноширинная латина, которую полюбливают японцы, тоже переводится в нижний регистр: ＡＢＣＤＥＦ → ａｂｃｄｅｆ.

**Comment by stalkerg** [comment]
перевёл все теги в нижний регистр

**Comment by stalkerg** [comment]
Думаю на этом багу можно закрыть.

**Comment by stalkerg** [comment]
Сделал.
