### ISSUE TITLE
Рекомендованные теги для картинок в статусе Pre

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#64]
Желательно, относить их к разделу "Рекомендованные теги", потому что окончательно они ещё не приняты.
В разделе "Принятые рек. тег" их можно только посмотреть, но по факту их можно удалить. Что позволяет сделать раздел "Рекомендованные теги".

**Comment by weyde** [comment]
тогда смысл всего раздела pre теряется, ибо остальные пользователи должны видеть что уже проставлено на изображении. а если мы все это в рекомендованные запихнем, то в чем тогда вообще смысл pre?

**Comment by iDolmatov** [comment]
Pre - это ведь не окончательный вариант. Модератор/пользователь могут убрать рекомендацию тега.
А разве пользователь видит теги в профиле пользователя?
https://anime-pictures.net/profile/view_ext_profile/25586?lang=ru
Не вижу такой функции. Это сделано для удобство самого пользователя.
-
Соседняя тема может позволить вообще всё в один раздел объединить, который смогут просматривать другие пользователи. Если это **действительно** нужно видеть другим пользователям.
Будет по аналогии с картинками пользователя: вверху отображение не проверенных рекомендаций тегов и для картинок с Pre. А ниже одобренные рекомендации.
Но такой вариант не предлагаю, ибо для картинки ещё можно разграничение сделать по статусу, а для тега уже сложнее.

**Comment by iDolmatov** [comment]
Пример рекомендации, которую в этом месяце делал:
Картинка: https://anime-pictures.net/pictures/view_post/241612?lang=ru
Теги: windows 7 && windows (operating system) && dreamlight2000 (cloverworkshop)
Когда загружена картинка? 2013 год
Когда рекомендовал? 2018 год
Где вижу? В принятых почти в конце списка (279 страница из 281 страниц), а не в начале. Ибо ориентир на дату картинки, а не на время рекомендации или одобрения.

**Comment by weyde** [comment]
и зачем оно нужно для пре так и не поняла. много шума, а смысла не видно за ним
вообще не могу понять вашых мыслей, особенно выделенных жирным (и ссылка не открывается)

**Comment by 7nik** [comment]
С такими мыслями давайте и для NEW-картинок добавлять теги через рекомендацию — это ведь тоже не окончательный вариант.  
Смысл рекомендации тега это возможность предложить добавить тег на _уже_ _проверенную_ картинку (модеры не сверхлюди чтобы добавлять все нужные теги, а тем более несуществовавшие на тот момент), а не писать об этом в комменты.

**Comment by iDolmatov** [comment]
Извини за "жир", это гитхаб так делает. Это из-за прочерка, который я привык использовать в формате горизонтальной линии.

Странно, что ссылка на мой профиль не открывается. Но разницы нет - подойдёт любой профиль. Суть в том, что проставленные и рекомендованные теги видит только сам пользователь, если не учитывать картинку.

> С такими мыслями давайте и для NEW-картинок добавлять теги через рекомендацию — это ведь тоже не окончательный вариант.
Не совсем верно. Для pre я ставлю теги, которые перепроверяет модератор.
Один пользователь может загрузить картинку и проставить минимум (автор, персонажи, м/ж). Модератор ставит пре, нужны ещё теги. Другой пользователь может добавить и удалить теги в этом статусе. 
Почему же он не может удалить тег без перехода к картинке, если возможность есть?

**Comment by 7nik** [comment]
1. Комменты на гитхабе можно редактировать после публикации.
2. Там есть preview коммента.
3. После цитаты нужно оставлять пустую строку, чтобы оно не превращалось в кашу.

Что на NEW, что на PRE приходит модератор и проверяет все теги и не важно кем они проставлены.
Мне лично было бы наоборот удобнее отменять рекомендацию с самой картинки, когда ты можешь на нее нормально посмотреть (или вообще открыть оригинал) и удостоверится, что этот тег не нужен, да вообще сразу видишь все теги картинки.

**Comment by iDolmatov** [comment]
Так то оно так, но это не отменяет того что тег находится в окончательных, а по факту нет и можно перейти на картинку, чтобы удалить тег. Поэтому и предложение, чтобы было в другом разделе.
___
На крайний случай, можно сделать так:
Один пункт по варианту текущих разделов. 
В одного колонке тег, во второй картинка, в третьей корзина.
Если тег можно удалить (поставлен на пре или рекомендован для полностью публичной), то корзина есть, иначе напротив тега и картинки пустая ячейка.

**Comment by 7nik** [comment]
Ну так с новыми картинками та же история, только баловаться так может только аплоадер. И в любом случае придёт модер приведёт всё в порядок и finita la commedia.

А была бы вся эта возможность реальной проблемой, мы уже задумались над её решением. А так это надуманная проблема.

**Comment by iDolmatov** [comment]
Это не проблема, как таковая. А просто желание, о чём говорит первое слово.
Просто смущает, что удаление есть в рекомендованных, а в пре только на самой картинке.
Думаю. что при вводе пре вообще не задумывались над этими разделами. Просто сделали: видно картинку, а пусть в принятых будет и усё, гуляй уася =)

**Comment by stalkerg** [comment]
Рекоммендованные теги и проставленные теги это разные таблицы в БД по этому они и не смешиваются нигде.
Если ты ставишь тег на картинку (пофигу пре или нет) то это попадает в одну таблицу, а если рекоммендуешь то в другую и программно с этим идёт работа совсем по разному.

**Comment by iDolmatov** [comment]
От оно как. Тогда закрываю тему.

**Comment by stalkerg** [comment]
В другом issue была отличная идея, просто выводить где то на странице уже рекоммендованные теги, часть вопроссов это должно снять, как и некоторый поиск в принятых тегах.
