### ISSUE TITLE
Цвета пользователей в блоке Now watching

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#7]
Обычные пользователи и модераторы имеют практически одинаковые цвета в блоке Now watching на оранжевой теме.
![image](https://user-images.githubusercontent.com/29704098/27533993-2ee216c2-5a6e-11e7-9e43-42d1b45e4d50.png)
Предлагаю использовать стандартные цвета ников.

**Comment by stalkerg** [comment]
Не очень понял. Что значит "стандартные цвета ников"?

**Comment by S-kidysh** [comment]
Видимо, стандартные, как в белой теме

**Comment by stalkerg** [comment]
Ок! Поправлю.

**Comment by 7nik** [comment]
Я имел ввиду цвета как на странице [о нас](https://anime-pictures.net/index/about?lang=ru). Там ты красный, модеры зелёные, коммитеры синие, а простые юзеры серые или оранжевые в зависимости от темы.

**Comment by stalkerg** [comment]
ну т.е. в итоге всё сводится к тому, что бы модеры были зелёными, а я крассным? (синий только в "о нас" используется)

**Comment by stalkerg** [comment]
Проверяйте, сделал.

**Comment by 7nik** [comment]
Ок, работает.

> синий только в "о нас" используется
[№506017](https://anime-pictures.net/pictures/view_post/506017?lang=ru), тут セルゲイ синий и как аплоадер, и как выставивший статус, и даже в комменте.
P.S.: Я смотрю коммитеры в топе пользователей не участвуют тоже)

**Comment by stalkerg** [comment]
Ага, вроде сделал. 

> P.S.: Я смотрю коммитеры тоже не участвуют в топе пользователей)

Да, это условия поподания в "О нас"
