### ISSUE TITLE
Стили курсоров

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#70]
Предлагаю добавить в CSS некоторым элементам атрибут курсора.
Думаю, это нужно, т.к. стиль "палец" кажется не всегда уместным.

`img.img_sp {
    cursor: zoom-in;
}`
или можно свой курсор прикрепить
`img.img_sp {
    cursor: url("http://img.t.sinajs.cn/t4/appstyle/photo/images/common/cur_zoom_in.cur"),auto;
}`

**Comment by 7nik** [comment]
Zoom-in курсор подразумевает просмотр увеличенного изображения на этой же странице. А "палец" это переход по ссылке — что собственно и происходит при нажатии на картинку.

**Comment by iDolmatov** [comment]
Это примеры кодов. Например, есть alias, который можно использовать для связанных картинок.
Если есть возможность, то можно нарисовать свои курсоры. Например, палец и две схожих картинки.
Если нельзя сделать или не будет смотреться, то достаточно узнать о такой идее.

**Comment by stalkerg** [comment]
> Думаю, это нужно, т.к. стиль "палец" кажется не всегда уместным.

у нас везде палец уместен может остальные не очень...

**Comment by MiTereKun** [comment]
можно табличный крестик, ([как тут](http://en.moepic.net)), при наведении, к примеру, на тег на странице view_post. Как раз таблица.
Как минимум не сильно логичным мне кажется отображения курсора текстового выделения ![](https://upload.wikimedia.org/wikipedia/ru/3/32/Css_cursor_text.png) при наведении на количество картинок. Я самого начала его воспринимал как курсор для работы с текстом, на некоторых сайтах его оставили только в поле ввода текста

**Comment by 7nik** [comment]
> таблица

Вообще там список, просто счётчики тегов немного отнесли в бок для удобства и красоты.

> курсор для работы с текстом

Всё правильно, этот курсор "говорит" что данный текст можно, как минимум, выделить, если только он не завёрнут в ссылку.

**Comment by iDolmatov** [comment]
Отказано общим обсуждением.
