### ISSUE TITLE
Paging of user comments is not working properly

### ISSUE THREAD

**Issue by Asovrix** [stalkerg/anime-pictures#71]
When you try to view the list of user comments, regardless if it is [All comments page](https://anime-pictures.net/pictures/view_all_comments/0) or comments for [any single user](https://anime-pictures.net/pictures/view_all_comments/0?by_user=1), the amount of comments shown per page is getting gradually higher as you approach the middle page (as in the case of stalkerg who has 40 pages of comments currently, it would be page nr 20) and starts going down from there.
If you look at comment dates, you will notice that you are gradually seeing more and more comments which should appear on previous or next pages.
On stalkerg's example:
- **Page 0**: 30 comments dating from 10/8/18 to 11/5/16 (mm/dd/yy)
- **Page 1**: 60 comments dating from 11/4/16 to 10/6/15
- **Page 2**: 90 comments dating from 5/22/16 to 12/26/14
- **Page 3**: 120 comments dating from 9/28/15 to 11/18/13
- [...]
- **Page 19**: 600 comments dating from 12/20/10 to 12/15/09
- **Page 20**: 610 comments dating from 10/8/10 to 10/11/09
- **Page 21**: 580 comments dating from 9/5/10 to 10/11/09
- [...]
- **Page 39**: 40 comments dating from 12/13/09 to 10/11/09
- **Page 40**: 10 comments dating from 10/15/09 to 10/11/09

As you might have noticed, pages 20-40 already show the very first comment made by him.

This might get **very bad** when you try to check for example page 325/650 from All comments page, which should in theory show 30 x 326 = 9780(!!) comments, if your web browser and website's server can handle this.

Since most of users browsing this Github are primarily Russian-speaking, feel free to answer here in Russian if you prefer so, I'll just use Google Translate.

**Comment by 7nik** [comment]
I suppose the bug appeared in July when stalkerg rewrote the page with comments.
Looks like incorrect calculation of a number of the last comment on a page.

I opened 505th (middle) page of all comments — the server answered with a delay in a few seconds but a tab quickly got hanged :D But investigating of the view-source page showed that there are nearly 15187 comments (°ロ°) !

**Comment by Asovrix** [comment]
> I opened 505th (middle) page of all comments
Uhhh... I appraise your bravery.
I just used this user CSS I wrote quickly for just this purpose if anyone wants to test this bug:
```
.comment_block tbody tr {counter-increment:comments}
.comment_block {counter-reset:comments}
.comment_block::after {
content:""counter(comments)" comments";
position:fixed;
font-size:16pt;
right:3px;
top:40px;
background:white;
color:blue
}
```
Guess what?
Page 324 shows this for me:
![chrome_2018-10-10_18-16-25](https://user-images.githubusercontent.com/44006686/46750743-f0c08e00-ccb8-11e8-9fc1-c45f5a94d11f.png)
Page 325 says 9711 comments.

**Comment by 7nik** [comment]
Note, I also see comments from banned pictures.
I wanted to execute `document.getElementById("comments").firstElementChild.children.length` but the tab hanged.

**Comment by stalkerg** [comment]
ouch, I fixed similar bug recently and check other parts but looks like skip this place. 
I will fix it ASAP.

**Comment by stalkerg** [comment]
fixed
