### ISSUE TITLE
Incorrect value for 2.39 aspect ratio is inserted when you click on it in advanced search

### ISSUE THREAD

**Issue by Asovrix** [stalkerg/anime-pictures#75]
As in title. When you click on "2.39" link in advanced search tool, instead of:
`2.39`
this gets inserted:
`2:39`
This results in no pictures found (_minimal_ resolution for an image to fit this criteria would need to be 800x15600).
Image for reference, with cursor over the troublesome link and the result of clicking it:
![chrome_2018-10-19_19-28-38](https://user-images.githubusercontent.com/44006686/47234235-70470f00-d3d5-11e8-9c85-1b0ee1d7e42e.png)
Oddly enough URL itself is correct when you open it in a new tab:

> https://anime-pictures.net/pictures/view_posts/0?aspect=2.39&lang=ru

**Comment by stalkerg** [comment]
I fixed, please check it again.

**Comment by Asovrix** [comment]
It's okay now. :) I wanted to mention this tiny issue in one of my previous ones, but I guess it was better to do it this way.
