### ISSUE TITLE
URLs in quote tags cause newline or space characters directly after it to be ignored

### ISSUE THREAD

**Issue by Asovrix** [stalkerg/anime-pictures#79]
When you write a comment/private or chat message with a multi line quote containing an URL, any newlines or normal spaces placed directly after it will get "eaten".
For example if you write:
```
[quote]https://example.com/
lorem ipsum
dolor sit amet[/quote]
```
You will get this:

> [https://example.com/](https://example.com/)lorem ipsum
> dolor sit amet

Even if you write:
```
[quote]https://example.com/      



lorem ipsum
dolor sit amet[/quote]
```
(do note spaces after the URL)
or:
```
[quote][url]https://example.com/[/url] 

lorem ipsum
dolor sit amet[/quote]
```
You will net the exact same result.

The only elegant way around this I can see is writing a [different kind of space](https://en.wikipedia.org/wiki/Non-breaking_space) directly after an URL and then putting a newline. Technically [any character not allowed in URLs](https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid) will make a newline not disappear.

Most recent example: https://anime-pictures.net/pictures/view_post/571617?lang=en (last comment by me)

**Comment by Asovrix** [comment]
Well... I remember this bug being present as long as I was using the site, which means at least since 2012.
I only remembered that it exists when I wrote the comment I mentioned.

**Comment by stalkerg** [comment]
I fixed it. Please check it.

**Comment by Asovrix** [comment]
It looks like it works correctly now. The comment I linked appeared as it should right away and after I edited it.

**Comment by stalkerg** [comment]
ok, good. It was strange logic in postmarkup lib for the first line.
