### ISSUE TITLE
Редактирование комментариев

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#8]
Редактирование комментария происходит в поле не связанном с кнопками BBCode'ов. А после редактирования комментария исчезают кнопки редактировать и удалить комментарий до перезагрузки страницы.

**Comment by iDolmatov** [comment]
Эхх. Всё ещё приходится обновлять страницу для повторного редактирования комментария.

**Comment by iDolmatov** [comment]
Исправлено в новой форме комментариев.
