### ISSUE TITLE
Abnormal avatar size

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#83]
Avatar of some users are bigger than should be and it slightly breaks site's makeup.
Examples of such users:
https://anime-pictures.net/profile/view_ext_profile/170677?lang=en
https://anime-pictures.net/profile/view_ext_profile/198268?lang=en

**Comment by stalkerg** [comment]
Looks like it's some bug in Pillow lib. I can't find any other reasons for that. Maybe income image in meta has some size/dpi information what effect to result.

**Comment by stalkerg** [comment]
make scale down by CSS for most places, as temp solution should be ok.
