### ISSUE TITLE
Поисковый плагин.xml

### ISSUE THREAD

**Issue by MiTereKun** [stalkerg/anime-pictures#88]
Мы пропустили добавления поискового плагина у гелбуру https://gelbooru.com/gelbooru.xml или как дугой пример - https://static.t-ru.org/opensearch.xml
Нам, как поисковику, такое не помешало бы и оно вроде делается относительно легко. Не у всех же хром, где не понятно как изменяются поисковые системы + возможно в будущем это получит большее развития в браузерах.
![image](https://user-images.githubusercontent.com/32958490/54580695-0b134a80-4a55-11e9-859b-12618ebc6ea3.png)

**Comment by stalkerg** [comment]
Добавил. Проверь пожалуйста.

**Comment by 7nik** [comment]
В Хроме и ФФ работает.

**Comment by stalkerg** [comment]
Спасибо!
