### ISSUE TITLE
Коллизия не английских тегов

### ISSUE THREAD

**Issue by 7nik** [stalkerg/anime-pictures#9]
Добавить защиту от коллизий тегов на всех языках (+ найти и исправить существующие).

**Comment by stalkerg** [comment]
Это когда англиский язык используется не в английской области?

**Comment by 7nik** [comment]
Нужно чтобы русское и японское название тоже были уникальными. К примеру, на днях было: 
![image](https://user-images.githubusercontent.com/29704098/27764183-c053809c-5e9b-11e7-817a-8cab7f445d13.png)
Второй тег обозначает что на картинке равно три человека, а первый - секс втроём. И ты не знаешь какой из них поставится, когда ты добавишь тег "трое")))
С авторскими яп. никами тоже иногда случается такой конфуз.

**Comment by stalkerg** [comment]
```
2 | золушка
     2 | с его стороны - с ее стороны
     2 | бэнто
     2 | носорог
     2 | акварион
     2 | джунгли
```

вот ещё коллизии, и ещё есть техничекие пустые строки на месте перевода но это фигня.

**Comment by stalkerg** [comment]
На японском куда хуже:
```
 count |            tag_jp            
-------+------------------------------
     2 | 豆芽菜
     2 | 一弦
     2 | 夜々
     2 | みどり
     2 | 薰
     2 | しおこんぶ
     2 | ガミュー
     2 | ☆若月
     2 | ねづみどし
     2 | 馬
     2 | けむけむ
     2 | カムクライズル
     2 | なつみ
     2 | 冷蝉
     2 | もり
     3 | ソラ
     2 | ずっき
     2 | め
     2 | 小松菜
     2 | 藤丸
     2 | うに
     2 | しば
     2 | ガールフレンド(仮)
     2 | 月影ネム
     2 | ひいろ
     3 | いろは
```
и ещё дофига, всего 215 тега, но кажись часто они оправданы т.к. это именна.
Т.е. в японском записываться может одними и темиже кандзями имя, а читаться по разному.

**Comment by stalkerg** [comment]
Русские коллизии кто разрулил? И что будем деать в итоге с японскими?
@7nik

**Comment by 7nik** [comment]
Пока никто не трогал.
А к японским авторским айди подописывать, остальные типы надо смотреть по месту.

**Comment by stalkerg** [comment]
Тогда я на тебя это вешаю. :) Позже полный список японских коллизий напишу, но пока и этих достаточно. 
Так а мне надо сделать проверку на колизии при переводе.

**Comment by stalkerg** [comment]
На данный момент есть 166 японских коллизий, уже конечно лучше.

**Comment by 7nik** [comment]
Как говорится, я сделал всё что мог.
Оставшиеся колизии:
魚, 翼, 紅 и 白 - это всё авторы с односимольными никами + ещё какой-нибудь тег, из-за которого я не смог добраться самих авторов.
ノワール - и копирайт и персонаж.
Теги которые уже не приводят к колизии, но я их не переименовывал потому, что они не относятся к авторам:
とと, 橙, キリアス, キキ, ニャース - персонажи;
アキラ - аниме;
リンゴ, マカロン - еда;
鳥居, やかん, 手袋, 手袋, 苦無 - объекты;
百足, スズメ - животные;
動物 - просто животное.

P.S.: раз пять попадались теги, у которых анг. название было фомата "иероглифы (artist)". Может стоит выцедить из базы теги в анг. названии которых есть не латиница?

**Comment by stalkerg** [comment]
Я тогда багу закрываю, в целом теперь всё ок. 

> раз пять попадались теги, у которых анг. название было фомата "иероглифы (artist)". Может стоит выцедить из базы теги в анг. названии которых есть не латиница?

тогда уж наоборот, только зачем?

**Comment by 7nik** [comment]
Я не правильно выразился. Я имею ввиду найти их и нормально обозвать. Те теги, которые попались мне, не имели других имён (как и описание), так что понять и найти их могли только японоговорящие.
