### ISSUE TITLE
Erotics in Prohibited Tags not working correctly for anonymous users

### ISSUE THREAD

**Issue by stalkerg** [stalkerg/anime-pictures#93]
Subj. Also, I should rewrite hacks for queries with "erotic" tags.

**Comment by stalkerg** [comment]
fixed

**Comment by MiTereKun** [comment]
честно вообще не понял что именно изменилось. Картинки как открывались не залогиненным по прямой ссылке - так и продолжают. Да это даже и хорошо, плохо то, что при переходе на такие картинки выбрасывает белый экран. Я бы поставил такую фигню только на лол&кон. По факту для защиты сайта от него и был предпринят данный шаг, сейчас можно только на него оставлять белый экран, а на остальные картинки писать такое же сообщение, как при входе в чат

**Comment by stalkerg** [comment]
тег эротика не работал в поле Запрещенные теги при поиске для анонимных пользователей.
