### ISSUE TITLE
Автоматическая обработка HTTP картинок в чате

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#95]
В сообщении пишешь HTTP, а при обработке получается HTTPS.
Понимаю, что HTTP уже устарел, но ещё встречаются сайты с поддержкой только HTTP.
Сегодня пробовал вставить в чат картинку, а он не подгружает - в логах ошибка ожидания ответа от сайта с картинкой.
`http://moemesto.ru/Alex_dolmatov/file/15127526/15112019.png`
P.S. Хотел предложить, чтобы сервер сайта делал запрос на проверку доступности домена картинки перед её показом, но неизвестно чревато ли это доп. нагрузкой на сайт и какое время ожидания оптимально, т.к. при наличии этой функции можно было бы показывать не BBimage со сломанной картинкой, а небольшую картинку невозможности показать картинку (с надписью или наглядно понятную) и уменьшить время проверки доступности за счёт обхода запроса браузера на проверку доступности ссылки.

**Comment by 7nik** [comment]
Хм, у меня в Хроме HTTP-картинки отображаются нормально, хоть и жалуется на Mixed Content. 
> ошибка ожидания ответа от сайта с картинкой.

Вообще это больше звучит как проблема со стороны хостинга, а не АР.
Будь это проблема использования HTTP на HTTPS-странице, то это было бы сказано в сообщении ошибки.

**Comment by iDolmatov** [comment]
Отредактировал сообщение в чате:
`[img]https://www.upload.speedrunwiki.com/images/misc/1511019.png[/img]
[img]http://moemesto.ru/Alex_dolmatov/file/15127526/15112019.png[/img]`
Видна только одна картинка.

`std.js?v=75:1 [Violation] Only request notification permission in response to a user gesture.
(anonymous) @ std.js?v=75:1
std.js?v=75:1 Permission wasn't granted. Allow a retry.
App.svelte:31 Open socket
App.svelte:62 all_users
App.svelte:62 last_messages
App.svelte:62 edit_message
moemesto.ru/Alex_dolmatov/file/15127526/15112019.png:1 GET https://moemesto.ru/Alex_dolmatov/file/15127526/15112019.png net::ERR_CONNECTION_TIMED_OUT`

Запрос браузера:
`fetch("https://moemesto.ru/Alex_dolmatov/file/15127526/15112019.png", {"credentials":"omit","referrer":"https://anime-pictures.net/chat/view?lang=ru","referrerPolicy":"no-referrer-when-downgrade","body":null,"method":"GET","mode":"cors"});`

**Comment by 7nik** [comment]
Надо было яснее сказать, что ссылка на картинку принудительно меняется с HTTP на HTTPS.

**Comment by stalkerg** [comment]
Да - так и есть т.к. это не безопасно с https ходить на http.
Это сразу приводит к тому что страница перестаёт быть полностью безопасной в глазах хрома. 
А так как система рендринга bbcode одна на весь сайт то и на чат работает. Кроме того кусок чата торчит на главной странице.

**Comment by MiTereKun** [comment]
если есть хоть одно http - сайт небезопасен даже в глазах тора, вместо перечёркнутого замка - перечёркнутый лук

**Comment by iDolmatov** [comment]
Спасибо за информацию. Буду считать это нюансом, который узнаёшь опытным путём.
