### ISSUE TITLE
Добавление BB кода URL в CODE

### ISSUE THREAD

**Issue by iDolmatov** [stalkerg/anime-pictures#97]
https://anime-pictures.net/pictures/view_post/519270
Писал комментарий с
`[code]https://usercontent.2th.me/a/d/game/59/4a/ce/f6/[2TH.me]_RJ045184_img_main.jpg[/code]`
Получил
`[url]https://usercontent.2th.me/a/d/game/59/4a/ce/f6/[/url][2TH.me]_RJ045184_img_main.jpg`

**Comment by 7nik** [comment]
ИМХО, там большая проблема в том, что ссылка определилась неправильно.

**Comment by iDolmatov** [comment]
Насколько понимаю, использование CODE не должно искать теги и ссылки внутри, чтобы показать текст без изменения.
Конечно, у сайта есть ограничение, что любые квадратные скобки считаются тегом. Именно из-за этого использовал тег кода.

**Comment by stalkerg** [comment]
Так как есть [2TH.me] то надо использовать [notag][/notag]

**Comment by iDolmatov** [comment]
Спасибо. Какое тогда назначение кода code?

**Comment by 7nik** [comment]
`[code]` должен форматировать текст моноширинным шрифтом, как тег `<code>`.
Вообще тут нужно было просто вручную завернуть ссылку в `[url]`.

**Comment by stalkerg** [comment]
Пока это можно назвать фичей с неявным поведением. В будущем мы попробуем уйти от bbCode.
